export const achievementsList = [
  {
    id: "first_challenge",
    title: "First Steps",
    description: "Complete your first challenge",
    icon: "Brain",
    xp: 50,
    gems: 10,
  },
  {
    id: "streak_3",
    title: "Hat Trick",
    description: "Maintain a 3-day streak",
    icon: "Flame",
    xp: 100,
    gems: 20,
  },
  {
    id: "streak_7",
    title: "Week Warrior",
    description: "Maintain a 7-day streak",
    icon: "Flame",
    xp: 200,
    gems: 50,
  },
  {
    id: "xp_500",
    title: "Brain Fuel",
    description: "Earn 500 total XP",
    icon: "Zap",
    xp: 100,
    gems: 25,
  },
  {
    id: "xp_1000",
    title: "Think Tank",
    description: "Earn 1,000 total XP",
    icon: "Zap",
    xp: 200,
    gems: 50,
  },
  {
    id: "all_categories",
    title: "Explorer",
    description: "Try all categories",
    icon: "Compass",
    xp: 150,
    gems: 30,
  },
  {
    id: "perfect_day",
    title: "Perfect Day",
    description: "Complete the daily challenge 5 days in a row",
    icon: "Sun",
    xp: 150,
    gems: 40,
  },
  {
    id: "level_5",
    title: "Rising Star",
    description: "Reach level 5",
    icon: "TrendingUp",
    xp: 300,
    gems: 75,
  },
  {
    id: "hearts_saver",
    title: "Heart Saver",
    description: "Complete a lesson without losing any hearts",
    icon: "Heart",
    xp: 100,
    gems: 20,
  },
  {
    id: "daily_goal_week",
    title: "On a Roll",
    description: "Hit your daily goal for 7 days",
    icon: "Target",
    xp: 250,
    gems: 60,
  },
] as const;
