import rawSeed from "./event-seed.json";
import type { EventQuestion, EventTheme } from "./event-theme";

const SEED_QUESTIONS: Record<string, EventQuestion> = {
  batman_day: {
    kicker: "THE RIDDLER ASKS",
    prompt: "In which city does Batman protect the innocent from the shadows?",
    options: ["Gotham City", "Metropolis", "Central City", "Star City"],
    xp: 30,
  },
  halloween: {
    kicker: "A SPOOKY RIDDLE",
    prompt: "Before pumpkins, what vegetable was carved into jack-o'-lanterns?",
    options: ["Turnips", "Apples", "Melons", "Potatoes"],
    xp: 30,
  },
  new_year: {
    kicker: "NEW YEAR QUIZ",
    prompt: "Which ancient civilization held the first known New Year festival, ~4000 years ago?",
    options: ["Romans", "Egyptians", "Babylonians", "Greeks"],
    xp: 30,
  },
  world_logic_day: {
    kicker: "A LOGIC PUZZLE",
    prompt: "All Bloops are Razzies, and all Razzies are Lazzies. So every Bloop is definitely a…?",
    options: ["Not a Lazzie", "Lazzie", "Sometimes a Lazzie", "Impossible to tell"],
    xp: 30,
  },
  puzzle_day: {
    kicker: "TODAY'S PUZZLER",
    prompt: "What is the best-selling puzzle toy of all time?",
    options: ["Rubik's Cube", "Jenga", "Tangram", "Sudoku book"],
    xp: 30,
  },
  valentines: {
    kicker: "A SWEET RIDDLE",
    prompt: "Which Roman festival is often cited as an early root of Valentine's Day?",
    options: ["Saturnalia", "Bacchanalia", "Floralia", "Lupercalia"],
    xp: 30,
  },
  pi_day: {
    kicker: "THE PI CHALLENGE",
    prompt: "What are the first three digits of π after the decimal point?",
    options: ["314", "159", "141", "161"],
    xp: 30,
  },
  earth_day: {
    kicker: "EARTH DAY QUIZ",
    prompt: "Roughly what share of Earth's surface is covered by water?",
    options: ["50%", "71%", "60%", "85%"],
    xp: 30,
  },
  star_wars_day: {
    kicker: "A GALACTIC RIDDLE",
    prompt: 'Complete the phrase: "May the ___ be with you."',
    options: ["Force", "Stars", "Light", "Power"],
    xp: 30,
  },
  yoga_day: {
    kicker: "A MINDFUL QUESTION",
    prompt: "In which country did the practice of yoga originate?",
    options: ["China", "Japan", "India", "Greece"],
    xp: 30,
  },
  emoji_day: {
    kicker: "EMOJI TRIVIA",
    prompt: "In which country were the first emoji created in the late 1990s?",
    options: ["USA", "Japan", "Finland", "South Korea"],
    xp: 30,
  },
  diwali: {
    kicker: "FESTIVAL OF LIGHTS",
    prompt: 'The word "Diwali" comes from "Deepavali", which means…?',
    options: ["Night of stars", "Day of joy", "Feast of sweets", "Row of lights"],
    xp: 30,
  },
  christmas: {
    kicker: "A FESTIVE RIDDLE",
    prompt: 'How many gifts are given in total across "The Twelve Days of Christmas"?',
    options: ["364", "78", "144", "100"],
    xp: 30,
  },
  new_years_eve: {
    kicker: "COUNTDOWN QUIZ",
    prompt: "Which city's Times Square ball drop is famously watched on New Year's Eve?",
    options: ["London", "New York", "Sydney", "Tokyo"],
    xp: 30,
  },
  thanksgiving: {
    kicker: "THANKSGIVING TRIVIA",
    prompt: "The 1621 harvest feast was shared between the Pilgrims and which Native American people?",
    options: ["Cherokee", "Sioux", "Wampanoag", "Apache"],
    xp: 30,
  },
  easter: {
    kicker: "EASTER QUIZ",
    prompt: "Which animal traditionally delivers eggs at Easter?",
    options: ["Lamb", "Bunny", "Chick", "Dove"],
    xp: 30,
  },
  holi: {
    kicker: "FESTIVAL OF COLOURS",
    prompt: "Holi joyfully celebrates the arrival of which season?",
    options: ["Summer", "Autumn", "Winter", "Spring"],
    xp: 30,
  },
  lunar_new_year: {
    kicker: "LUNAR NEW YEAR",
    prompt: "The Lunar New Year zodiac cycles through how many animals?",
    options: ["10", "12", "7", "15"],
    xp: 30,
  },
  hanukkah: {
    kicker: "A HANUKKAH RIDDLE",
    prompt: "How many candles does a Hanukkah menorah hold in total, including the helper?",
    options: ["7", "8", "9", "12"],
    xp: 30,
  },
  education_day: {
    kicker: "CLASS IS IN SESSION",
    prompt: "Which study trick is actually proven to help you remember more?",
    options: ["Cramming all night", "Spacing it out over days", "Highlighting everything", "Reading it once"],
    xp: 30,
  },
  women_in_science: {
    kicker: "SCIENCE SUPERSTAR",
    prompt: "Marie Curie is the only person to win Nobel Prizes in two different sciences. Which two?",
    options: ["Physics & Chemistry", "Biology & Physics", "Chemistry & Medicine", "Physics & Medicine"],
    xp: 30,
  },
  world_radio_day: {
    kicker: "ON THE AIRWAVES",
    prompt: "Before podcasts and playlists, families would gather around the radio for what?",
    options: ["Silent films", "Live radio dramas", "TV news", "Video calls"],
    xp: 30,
  },
  kindness_acts: {
    kicker: "PAY IT FORWARD",
    prompt: "Doing something kind for a stranger gives your brain a boost often called…?",
    options: ["A sugar rush", "The helper's high", "Brain freeze", "A second wind"],
    xp: 30,
  },
  mother_language_day: {
    kicker: "MIND YOUR LANGUAGE",
    prompt: "Roughly how many languages are spoken around the world today?",
    options: ["Around 700", "Around 7,000", "Around 70", "Around 70,000"],
    xp: 30,
  },
  womens_day: {
    kicker: "HERE'S TO HER",
    prompt: "Which colour is most associated with International Women's Day?",
    options: ["Red", "Green", "Purple", "Blue"],
    xp: 30,
  },
  kidney_day: {
    kicker: "BODY TRIVIA",
    prompt: "Most people are born with two kidneys, but how many can you live healthily with?",
    options: ["Two, no fewer", "Just one", "You need three", "Half of one"],
    xp: 30,
  },
  happiness_day: {
    kicker: "SMILE CHECK",
    prompt: "Studies say one of the fastest ways to feel happier is to…?",
    options: ["Buy something new", "Scroll your phone", "Thank someone", "Win an argument"],
    xp: 30,
  },
  world_health_day: {
    kicker: "STAY WELL",
    prompt: "Which simple free habit is linked to a longer, healthier life more than almost anything?",
    options: ["Daily walking", "Skipping breakfast", "Sitting more", "Late-night snacks"],
    xp: 30,
  },
  creativity_day: {
    kicker: "BRIGHT IDEA",
    prompt: "Great ideas often strike in the shower because your brain is…?",
    options: ["Overloaded", "Relaxed and wandering", "Fast asleep", "Panicking"],
    xp: 30,
  },
  book_day: {
    kicker: "SHELF LIFE",
    prompt: "What is the best-selling novel of all time?",
    options: ["Don Quixote", "The Hobbit", "1984", "Moby-Dick"],
    xp: 30,
  },
  light_day: {
    kicker: "LET THERE BE LIGHT",
    prompt: "How long does light from the Sun take to reach your eyes on Earth?",
    options: ["About 8 minutes", "Instantly", "About 8 hours", "About 8 seconds"],
    xp: 30,
  },
  bee_day: {
    kicker: "BUZZ BUZZ",
    prompt: "How do honeybees tell each other where the best flowers are?",
    options: ["They sing", "A waggle dance", "They leave a trail", "They text"],
    xp: 30,
  },
  geek_pride: {
    kicker: "ROLL FOR TRIVIA",
    prompt: "Geek Pride Day shares its date with the release of which sci-fi classic?",
    options: ["Star Trek", "Star Wars", "The Matrix", "Blade Runner"],
    xp: 30,
  },
  mothers_day: {
    kicker: "THANKS, MUM",
    prompt: "Which flower is the classic symbol of Mother's Day?",
    options: ["Rose", "Carnation", "Tulip", "Daisy"],
    xp: 30,
  },
  environment_day: {
    kicker: "GO GREEN",
    prompt: "Which everyday action saves the most water at home?",
    options: ["Shorter showers", "Tap off while brushing", "Fixing a leaky tap", "All of these together"],
    xp: 30,
  },
  oceans_day: {
    kicker: "DEEP DIVE",
    prompt: "Roughly how much of the oxygen you breathe comes from the ocean?",
    options: ["About 10%", "About half", "About 5%", "Almost none"],
    xp: 30,
  },
  music_day: {
    kicker: "TURN IT UP",
    prompt: "Listening to a song you love releases which feel-good brain chemical?",
    options: ["Dopamine", "Insulin", "Melatonin", "Adrenaline"],
    xp: 30,
  },
  fathers_day: {
    kicker: "THANKS, DAD",
    prompt: "The classic 'dad joke' is famous for being…?",
    options: ["Terrifying", "Groan-worthy puns", "Deeply serious", "Impossible to hear"],
    xp: 30,
  },
  chocolate_day: {
    kicker: "SWEET TOOTH",
    prompt: "Chocolate is made from the seeds of which tree?",
    options: ["Coconut", "Cacao", "Coffee", "Cashew"],
    xp: 30,
  },
  moon_day: {
    kicker: "ONE GIANT LEAP",
    prompt: "Who was the first person to walk on the Moon, back in 1969?",
    options: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"],
    xp: 30,
  },
  friendship_day: {
    kicker: "BESTIES FOREVER",
    prompt: "Strong friendships are linked to which surprising health benefit?",
    options: ["A longer life", "Getting taller", "Better eyesight", "Faster typing"],
    xp: 30,
  },
  sunflower_day: {
    kicker: "FOLLOW THE SUN",
    prompt: "Young sunflowers do something amazing all day — they…?",
    options: ["Glow at night", "Turn to follow the sun", "Close up completely", "Change colour"],
    xp: 30,
  },
  cat_day: {
    kicker: "PURR-FECT QUIZ",
    prompt: "Cats purr when happy — but here's the twist, they also purr to…?",
    options: ["Scare dogs", "Self-soothe and heal", "Show anger only", "Sing"],
    xp: 30,
  },
  book_lovers_day: {
    kicker: "FOR THE READERS",
    prompt: "What's the word for the lovely smell of old books?",
    options: ["Petrichor", "Bibliosmia", "Nostalgia", "Mustiness"],
    xp: 30,
  },
  youth_day: {
    kicker: "YOUNG & UNSTOPPABLE",
    prompt: "Who became the youngest-ever Nobel Peace Prize winner, at just 17?",
    options: ["Greta Thunberg", "Malala Yousafzai", "Anne Frank", "Joan of Arc"],
    xp: 30,
  },
  photography_day: {
    kicker: "SAY CHEESE",
    prompt: "Roughly how many photos do people take worldwide every single day?",
    options: ["Millions", "Billions", "Thousands", "Hundreds"],
    xp: 30,
  },
  elephant_day: {
    kicker: "GENTLE GIANTS",
    prompt: "Elephants greet old friends and even mourn their dead. This shows they have…?",
    options: ["Poor memory", "Deep emotions & memory", "No social life", "Bad hearing"],
    xp: 30,
  },
  literacy_day: {
    kicker: "WORD POWER",
    prompt: "Reading regularly has been shown to do what for your brain?",
    options: ["Shrink it", "Boost empathy & focus", "Nothing at all", "Cause headaches"],
    xp: 30,
  },
  pirate_day: {
    kicker: "AHOY, MATEY",
    prompt: "What does a pirate famously shout?",
    options: ["Bonjour!", "Arrr!", "Aloha!", "Cheerio!"],
    xp: 30,
  },
  peace_day: {
    kicker: "MAKE PEACE",
    prompt: "The famous peace symbol was first designed in the 1950s to protest what?",
    options: ["Traffic", "Nuclear weapons", "Homework", "High taxes"],
    xp: 30,
  },
  heart_day: {
    kicker: "MATTERS OF THE HEART",
    prompt: "About how many times does your heart beat in a single day?",
    options: ["About 1,000", "About 100,000", "About 100", "About 10 million"],
    xp: 30,
  },
  coffee_day: {
    kicker: "BUT FIRST, COFFEE",
    prompt: "Which country grows the most coffee in the world?",
    options: ["Italy", "Brazil", "USA", "Ethiopia"],
    xp: 30,
  },
  teachers_day: {
    kicker: "TOP OF THE CLASS",
    prompt: "The best kind of teacher is someone who…?",
    options: ["Knows every answer", "Sparks your curiosity", "Talks the most", "Gives no homework"],
    xp: 30,
  },
  mental_health_day: {
    kicker: "MIND MATTERS",
    prompt: "Which simple thing genuinely helps your mind on a tough day?",
    options: ["Bottling it up", "Talking to someone", "Skipping sleep", "Ignoring it"],
    xp: 30,
  },
  science_day: {
    kicker: "EUREKA!",
    prompt: "Every great scientific discovery starts with which of these?",
    options: ["A conclusion", "A curious question", "A trophy", "A textbook"],
    xp: 30,
  },
  kindness_day: {
    kicker: "SPREAD IT",
    prompt: "Kindness is contagious — seeing someone be kind makes you more likely to…?",
    options: ["Ignore others", "Be kind too", "Feel worse", "Do nothing"],
    xp: 30,
  },
  friday_13th: {
    kicker: "SPOOKY NUMBERS",
    prompt: "What's the tongue-twisting name for the fear of Friday the 13th?",
    options: ["Arachnophobia", "Paraskevidekatriaphobia", "Claustrophobia", "Acrophobia"],
    xp: 30,
  },
  childrens_day: {
    kicker: "STAY PLAYFUL",
    prompt: "What do experts consider the most important 'work' of childhood?",
    options: ["Chores", "Play", "Sitting still", "Filing taxes"],
    xp: 30,
  },
  human_rights_day: {
    kicker: "RIGHTS FOR ALL",
    prompt: "Human rights belong to…?",
    options: ["Only adults", "Every single person", "Only citizens", "The wealthy"],
    xp: 30,
  },
  winter_solstice: {
    kicker: "LONGEST NIGHT",
    prompt: "The winter solstice is famous for being the year's…?",
    options: ["Hottest day", "Shortest day", "Longest day", "Windiest day"],
    xp: 30,
  },
};

export const SEED_EVENTS: EventTheme[] = (rawSeed as EventTheme[]).map((e) => {
  const question = SEED_QUESTIONS[e.id];
  return question ? { ...e, question } : e;
});

export const SEED_QUESTION_IDS = new Set(Object.keys(SEED_QUESTIONS));
