// AUTO-GENERATED by scripts/seed-data/gen-ciphers.mjs. DO NOT EDIT BY HAND.
//
// Every encodedMessage below was encoded and round-trip decoded back to its
// plaintext at generation time, so no ciphertext here can be wrong. To change
// cipher content, edit gen-ciphers.mjs and re-run it.
//
// Consumed by the Studio "Load Ciphers" tool (app/studio/ciphers/page.tsx),
// which upserts each entry into Firestore by its stable `id` (additive: it
// never wipes the puzzle bank).

import type { SeedPuzzleInput } from "./importer";

export interface CipherSeedInput extends SeedPuzzleInput {
  id: string;
}

export const cipherSeeds: CipherSeedInput[] = [
  {
    "id": "cipher-first-transmission",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "First Transmission",
    "question": "",
    "correctAnswer": "stay in the shadows",
    "acceptedAnswers": [
      "stay in the shadows",
      "stayintheshadows"
    ],
    "xpReward": 130,
    "cipherData": {
      "encodedMessage": "... - .- -.-- / .. -. / - .... . / ... .... .- -.. --- .-- ...",
      "cipherType": "Morse Code",
      "hint": "The oldest electric dialect confesses in nothing but the brief and the sustained; honour the caesura between them."
    },
    "correctExplanation": "This is International Morse Code. A single space separates letters and ' / ' separates words. Decoded, the message reads 'stay in the shadows'.",
    "incorrectExplanation": "Read the dots and dashes as Morse. Single spaces break letters; the ' / ' marks break words. Map each group back to its letter using a Morse table."
  },
  {
    "id": "cipher-zig-zag-fence",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Zig-Zag Fence",
    "question": "",
    "correctAnswer": "the walls have ears",
    "acceptedAnswers": [
      "the walls have ears",
      "thewallshaveears"
    ],
    "xpReward": 130,
    "cipherData": {
      "encodedMessage": "tahehwlsaeaselvr",
      "cipherType": "Rail Fence (3 rails)",
      "hint": "Nothing was disguised, only made to descend and ascend across a palisade of three tiers before being harvested tier by tier."
    },
    "correctExplanation": "This is a Rail Fence transposition on 3 rails. The plaintext zig-zags down and up across 3 lines, then each line is read out in order. Reconstruct the zig-zag path to recover 'the walls have ears'.",
    "incorrectExplanation": "No letters were substituted, only reordered. This is a Rail Fence cipher on 3 rails: the plaintext zig-zags down and up across 3 lines, then each line is read out. Rebuild the zig-zag to undo it."
  },
  {
    "id": "cipher-locksmiths-riddle",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Locksmith's Riddle",
    "question": "",
    "correctAnswer": "a piano",
    "acceptedAnswers": [
      "a piano",
      "piano"
    ],
    "xpReward": 140,
    "cipherData": {
      "encodedMessage": "23 8 1 20  8 1 19  11 5 25 19  2 21 20  15 16 5 14 19  14 15  12 15 3 11 19",
      "cipherType": "A1Z26 + Riddle",
      "hint": "Each ordinal is merely its letter's rank in the alphabet; the sentence you recover is itself an enigma, and the true answer lies one riddle deeper."
    },
    "correctExplanation": "Map each number to a letter (1=A ... 26=Z, double spaces mark word breaks): the message decodes to 'what has keys but opens no locks'. The answer to that riddle is a piano, whose keys make music, not entry.",
    "incorrectExplanation": "First convert the numbers to letters (1=A ... 26=Z, double spaces = new word). That reveals a riddle: 'what has keys but opens no locks'. The final answer is not the decoded sentence, it is the solution to the riddle."
  },
  {
    "id": "cipher-keyword-of-the-gods",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "Keyword of the Gods",
    "question": "",
    "correctAnswer": "only the worthy may pass",
    "acceptedAnswers": [
      "only the worthy may pass"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "CFTP BZS OWIBZM EIP XSGK",
      "cipherType": "Vigenere",
      "hint": "A repeating watchword drives this many-alphabet drift. Seek the green-skinned arbiter of the Duat who weighs hearts against a feather; his six letters are your key."
    },
    "correctExplanation": "The god is OSIRIS (6 letters). Using OSIRIS as a Vigenere keyword and shifting each ciphertext letter backward by the keyword letter's alphabet position, the message decodes to 'only the worthy may pass'.",
    "incorrectExplanation": "This is a Vigenere cipher. Identify the six-letter keyword (the Egyptian god of the afterlife is OSIRIS), align it repeatedly under the ciphertext, and shift each letter backward by the keyword letter's position (A=0, B=1 ... Z=25)."
  },
  {
    "id": "cipher-chamber-grid",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Chamber Grid",
    "question": "",
    "correctAnswer": "secrets keep",
    "acceptedAnswers": [
      "secrets keep",
      "secretskeep"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "43 15 13 42 15 44 43 25 15 15 35",
      "cipherType": "Polybius Square",
      "hint": "Every pair is a latitude and longitude upon a five-by-five lattice bearing the alphabet in sequence, where the twins I and J are forced to cohabit one cell."
    },
    "correctExplanation": "This is a Polybius square: fill a 5x5 grid A-Z left-to-right (I/J share a cell), then read each digit pair as (row, column). The coordinates decode to 'secrets keep'.",
    "incorrectExplanation": "Each two-digit number is a coordinate. Build a 5x5 grid with the alphabet in order (combine I/J), read the first digit as the row and the second as the column, and look up each letter."
  },
  {
    "id": "cipher-two-locks-one-door",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "Two Locks, One Door",
    "question": "",
    "correctAnswer": "follow the north star",
    "acceptedAnswers": [
      "follow the north star"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "bXZzc3ZkIGFvbCB1dnlhbyB6YWh5",
      "cipherType": "Base64 + Caesar",
      "hint": "The outer husk is the six-bit armour machines don to ferry bytes unscathed; peel it and a Roman general's uniform displacement still bars the way."
    },
    "correctExplanation": "Layer one is Base64. Decoding it yields text that is still shifted by a Caesar cipher of +7. Shift each letter back by 7 to get 'follow the north star'.",
    "incorrectExplanation": "The mixed-case block is the giveaway for Base64, so decode that first. The result is still gibberish because a Caesar shift of 7 sits underneath. Undo the shift to finish."
  },
  {
    "id": "cipher-ones-and-zeroes",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "Ones and Zeroes",
    "question": "",
    "correctAnswer": "the phoenix rises at dusk",
    "acceptedAnswers": [
      "the phoenix rises at dusk"
    ],
    "xpReward": 160,
    "cipherData": {
      "encodedMessage": "01100111 01110011 01110110 00100000 01101011 01110011 01101100 01110110 01101101 01110010 01100011 00100000 01101001 01110010 01101000 01110110 01101000 00100000 01111010 01100111 00100000 01110111 01100110 01101000 01110000",
      "cipherType": "Binary + Atbash",
      "hint": "Gather the base-two glyphs into octets and read them as machine characters; what emerges is still ensnared by the ancient Hebrew looking-glass that folds A onto Z."
    },
    "correctExplanation": "Each 8-bit group is an ASCII character. Converting the binary gives text still encrypted with Atbash (A to Z, B to Y, C to X ...). Applying Atbash reveals 'the phoenix rises at dusk'.",
    "incorrectExplanation": "Read each group of 8 bits as a byte and convert to ASCII text first. The result is still encrypted with Atbash, the alphabet reversed onto itself. Mirror each letter to finish."
  },
  {
    "id": "cipher-cartographers-cipher",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Cartographer's Cipher",
    "question": "",
    "correctAnswer": "footsteps",
    "acceptedAnswers": [
      "footsteps",
      "foot steps"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "74 68 65 20 6d 6f 72 65 20 79 6f 75 20 74 61 6b 65 20 74 68 65 20 6d 6f 72 65 20 79 6f 75 20 6c 65 61 76 65 20 62 65 68 69 6e 64",
      "cipherType": "Hexadecimal + Riddle",
      "hint": "Read the base-sixteen couplets as the tint-and-character code every screen obeys; the sentence unveiled is a paradox, and its resolution is what you seek."
    },
    "correctExplanation": "Each hex pair is an ASCII code (20 is a space). Decoded, it reads 'the more you take the more you leave behind'. The answer to that riddle is footsteps.",
    "incorrectExplanation": "Convert each two-digit hexadecimal number to its ASCII character (20 is a space). That spells a riddle: 'the more you take the more you leave behind'. The final answer is the riddle's solution, not the decoded line."
  },
  {
    "id": "cipher-seamstress-paradox",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Seamstress's Paradox",
    "question": "",
    "correctAnswer": "a needle",
    "acceptedAnswers": [
      "a needle",
      "needle"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "77 68 61 74 20 68 61 73 20 61 6e 20 65 79 65 20 62 75 74 20 63 61 6e 6e 6f 74 20 73 65 65",
      "cipherType": "Hexadecimal + Riddle",
      "hint": "Interpret each base-sixteen duet as the glyph-code every display obeys; the aphorism it exhumes is a paradox, and its resolution, not the sentence, is your quarry."
    },
    "correctExplanation": "Each hex pair is an ASCII code (20 is a space). Decoded it reads 'what has an eye but cannot see'. The answer to that riddle is a needle, whose eye holds thread, not sight.",
    "incorrectExplanation": "Convert each two-digit hexadecimal number to its ASCII character (20 is a space). That spells the riddle 'what has an eye but cannot see'. The final answer is the riddle's solution, not the decoded line."
  },
  {
    "id": "cipher-absorbent-enigma",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Absorbent Enigma",
    "question": "",
    "correctAnswer": "a towel",
    "acceptedAnswers": [
      "a towel",
      "towel"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "23 8 1 20  7 5 20 19  23 5 20 20 5 18  20 8 5  13 15 18 5  9 20  4 18 9 5 19",
      "cipherType": "A1Z26 + Riddle",
      "hint": "Every integer is nothing but its letter's station in the alphabet; the twin gaps sever the words. What surfaces is a contradiction whose solution you must name."
    },
    "correctExplanation": "Map each number to a letter (double spaces mark word breaks): the message decodes to 'what gets wetter the more it dries'. The answer is a towel, which soaks up water while drying you.",
    "incorrectExplanation": "First convert the numbers to letters (1=A ... 26=Z, double spaces mark word breaks). That reveals a riddle: 'what gets wetter the more it dries'. The final answer is the riddle's solution, not the decoded line."
  },
  {
    "id": "cipher-tolling-signal",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Tolling Signal",
    "question": "",
    "correctAnswer": "a clock",
    "acceptedAnswers": [
      "a clock",
      "clock"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": ".-- .... .- - / .... .- ... / .... .- -. -.. ... / -... ..- - / -.-. .- -. -. --- - / -.-. .-.. .- .--.",
      "cipherType": "Morse + Riddle",
      "hint": "The staccato dialect of the wire yields a conundrum once you honour its brief-and-sustained pulses and the slashes cleaving word from word; the answer lies past the sentence."
    },
    "correctExplanation": "Read the Morse (' / ' marks word breaks) to get the riddle 'what has hands but cannot clap'. The answer is a clock.",
    "incorrectExplanation": "Decode the Morse first, single spaces break letters and ' / ' breaks words, to get the riddle 'what has hands but cannot clap'. The final answer is the riddle's solution: a clock."
  },
  {
    "id": "cipher-vessels-riddle",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Vessel's Riddle",
    "question": "",
    "correctAnswer": "a bottle",
    "acceptedAnswers": [
      "a bottle",
      "bottle"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "52 23 11 44 23 11 43 11 33 15 13 25 12 45 44 33 34 23 15 11 14",
      "cipherType": "Polybius Square + Riddle",
      "hint": "Each numeral pair is a coordinate on a five-by-five lattice bearing the alphabet in order, the twins I and J sharing one cell; the recovered line is a riddle whose answer you must supply."
    },
    "correctExplanation": "Build a 5x5 Polybius grid (A-Z in order, I/J share a cell); each pair is (row, column). It decodes to 'what has a neck but no head'. The answer is a bottle.",
    "incorrectExplanation": "Each two-digit number is a coordinate on a 5x5 grid filled with the alphabet in order (I/J combined): first digit is the row, second the column. That spells 'what has a neck but no head'. The final answer is the riddle's solution: a bottle."
  },
  {
    "id": "cipher-mirrored-alphabet",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Mirrored Alphabet",
    "question": "",
    "correctAnswer": "guard the gate at midnight",
    "acceptedAnswers": [
      "guard the gate at midnight"
    ],
    "xpReward": 140,
    "cipherData": {
      "encodedMessage": "tfziw gsv tzgv zg nrwmrtsg",
      "cipherType": "Atbash",
      "hint": "No letter kept its seat; each was reflected across the alphabet's axis, so the first becomes the last and the fifth from the front the fifth from the rear (A to Z, B to Y)."
    },
    "correctExplanation": "This is Atbash, the alphabet reversed onto itself (A to Z, B to Y, C to X ...). Mirroring each letter reveals 'guard the gate at midnight'.",
    "incorrectExplanation": "No letters were shifted by a fixed amount; the whole alphabet is mirrored (A to Z, B to Y, C to X ...). Replace each letter with its mirror-image partner to recover the message."
  },
  {
    "id": "cipher-serpent-fence",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Serpent Fence",
    "question": "",
    "correctAnswer": "cross the river at dawn",
    "acceptedAnswers": [
      "cross the river at dawn",
      "crosstheriveratdawn"
    ],
    "xpReward": 140,
    "cipherData": {
      "encodedMessage": "chrnrteeawosrvtasid",
      "cipherType": "Rail Fence (4 rails)",
      "hint": "A serpent taller than the last coils across four tiers, not three. Trace its scaled descent and rise before you gather each row."
    },
    "correctExplanation": "This is a Rail Fence transposition on 4 rails. The plaintext zig-zags across 4 lines, then each line is read in order. Rebuild the four-rail zig-zag to recover 'cross the river at dawn'.",
    "incorrectExplanation": "No letters changed, only their order. This is a Rail Fence cipher, but on 4 rails rather than 3. Map the ciphertext back onto a four-line zig-zag to undo it."
  },
  {
    "id": "cipher-ledger-of-bacon",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Ledger of Bacon",
    "question": "",
    "correctAnswer": "hidden in plain sight",
    "acceptedAnswers": [
      "hidden in plain sight",
      "hiddeninplainsight"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "aabbb abaaa aaabb aaabb aabaa abbaa abaaa abbaa abbba ababa aaaaa abaaa abbaa baaab abaaa aabba aabbb baaba",
      "cipherType": "Baconian",
      "hint": "A philosopher-statesman hid letters inside a binary of two typefaces. Each character is five marks of only two kinds; read a and b as nought and one."
    },
    "correctExplanation": "This is the Baconian cipher: every letter is a group of five a/b marks (a 24-letter alphabet where I/J and U/V share a code). Decoding each five-mark group spells 'hidden in plain sight'.",
    "incorrectExplanation": "Each letter is encoded as five symbols of two kinds (a and b). Split the stream into groups of five, treat a=0 and b=1, and map each 5-bit group to its letter using Bacon's 24-letter alphabet."
  },
  {
    "id": "cipher-apothecarys-formula",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Apothecary's Formula",
    "question": "",
    "correctAnswer": "trust no one here",
    "acceptedAnswers": [
      "trust no one here"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "ZPEUZ VA AVC RCPC",
      "cipherType": "Affine (a=5, b=8)",
      "hint": "Each letter was passed through a formula: multiply its position, then add a fixed dose. The multiplier is five and the additive is eight. To undo it you must divide, which on a ring of twenty-six means multiplying by an inverse."
    },
    "correctExplanation": "This is an Affine cipher with a=5, b=8. Encoding maps each letter position x to (5x + 8) mod 26. To reverse it, multiply by the modular inverse of 5 (which is 21) after subtracting 8. The message decodes to 'trust no one here'.",
    "incorrectExplanation": "This is an Affine cipher: each letter position x became (a*x + b) mod 26 with a=5 and b=8. Decrypt with x = ainv * (y - b) mod 26, where ainv is the modular inverse of 5 mod 26 (that is 21)."
  },
  {
    "id": "cipher-wardens-columns",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Warden's Columns",
    "question": "",
    "correctAnswer": "beware the ides of march",
    "acceptedAnswers": [
      "beware the ides of march",
      "bewaretheidesofmarch"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "RIFHWHSRETEAAEOCBEDM",
      "cipherType": "Columnar Transposition (key ZEBRA)",
      "hint": "Write the message in rows beneath a five-letter keyword, then read the columns not left to right but in the alphabetical order of that word. The keyword is a striped beast of the plains."
    },
    "correctExplanation": "This is a Columnar Transposition with the keyword ZEBRA. The plaintext is written in rows of five, then columns are read in the alphabetical order of the keyword letters (A, B, E, R, Z). Reversing that reordering recovers 'beware the ides of march'.",
    "incorrectExplanation": "No letters were substituted. Write the ciphertext back into columns, ordering them by the alphabetical rank of the keyword ZEBRA (A=1, B=2, E=3, R=4, Z=5), then read across the rows."
  },
  {
    "id": "cipher-eye-of-horus",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Eye of Horus",
    "question": "",
    "correctAnswer": "the eye sees all things",
    "acceptedAnswers": [
      "the eye sees all things"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "AVV YQL GVYK HZC NZPBXM",
      "cipherType": "Vigenere",
      "hint": "A repeating watchword drives this drift of many alphabets. The falcon-headed sky god whose wounded eye became a symbol of protection lends his five letters as the key."
    },
    "correctExplanation": "The keyword is HORUS (5 letters). Aligning it repeatedly under the ciphertext and shifting each letter backward by the keyword letter's position decodes the message to 'the eye sees all things'.",
    "incorrectExplanation": "This is a Vigenere cipher. The five-letter keyword is the falcon-headed Egyptian god HORUS. Repeat it under the ciphertext and shift each letter backward by the keyword letter's alphabet position."
  },
  {
    "id": "cipher-mirror-vault",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Mirror Vault",
    "question": "",
    "correctAnswer": "knowledge is power",
    "acceptedAnswers": [
      "knowledge is power"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "cG1sZG92d3R2IHJoIGtsZHZp",
      "cipherType": "Base64 + Atbash",
      "hint": "The outer shell is the six-bit armour machines wear to carry bytes intact. Peel it, and behind lies the ancient looking-glass alphabet that folds A onto Z."
    },
    "correctExplanation": "Layer one is Base64. Decoding it yields text still under Atbash (A to Z, B to Y ...). Mirroring the alphabet reveals 'knowledge is power'.",
    "incorrectExplanation": "Decode the Base64 first. The result is still enciphered with Atbash, the alphabet reversed onto itself. Mirror each letter to finish."
  },
  {
    "id": "cipher-silent-dispatch",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Silent Dispatch",
    "question": "",
    "correctAnswer": "retreat before dawn breaks",
    "acceptedAnswers": [
      "retreat before dawn breaks"
    ],
    "xpReward": 160,
    "cipherData": {
      "encodedMessage": "-... .-. . .- -.- ... / -.. .- .-- -. / -... . ..-. --- .-. . / .-. . - .-. . .- -",
      "cipherType": "Morse Code (reversed words)",
      "hint": "First the wire speaks in brief and sustained pulses; but a cunning sender also marched the words out backwards. Decode the dots and dashes, then read the words in reverse to set them right."
    },
    "correctExplanation": "Decode the Morse (' / ' separates words) to get the words, then reverse their order: the message becomes 'retreat before dawn breaks'.",
    "incorrectExplanation": "Two steps: decode the Morse first (single space between letters, ' / ' between words), then reverse the order of the recovered words to restore the true message."
  },
  {
    "id": "cipher-astronomers-riddle",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Astronomer's Riddle",
    "question": "",
    "correctAnswer": "a map",
    "acceptedAnswers": [
      "a map",
      "map"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "69 20 68 61 76 65 20 63 69 74 69 65 73 20 62 75 74 20 6e 6f 20 68 6f 75 73 65 73 20 66 6f 72 65 73 74 73 20 62 75 74 20 6e 6f 20 74 72 65 65 73",
      "cipherType": "Hexadecimal + Riddle",
      "hint": "Read the base-sixteen couplets as the character code every screen obeys. The sentence you recover is a riddle, and only its answer will open the way."
    },
    "correctExplanation": "Each hex pair is an ASCII code (20 is a space). Decoded it reads 'i have cities but no houses forests but no trees'. The answer to that riddle is a map.",
    "incorrectExplanation": "Convert each two-digit hexadecimal number to its ASCII character (20 is a space). That reveals a riddle. The final answer is the riddle's solution, a map, not the decoded sentence."
  },
  {
    "id": "cipher-sentinels-word",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Sentinel's Word",
    "question": "",
    "correctAnswer": "the vault opens at noon",
    "acceptedAnswers": [
      "the vault opens at noon"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "LOE YOQDA OSSJK HT QCKF",
      "cipherType": "Vigenere",
      "hint": "A repeating watchword steers this many-alphabet drift. The key is the very thing a sentinel keeps to at dusk and the name this whole game wears: what a wall casts when the light is behind it."
    },
    "correctExplanation": "The keyword is SHADOW (6 letters). Aligning it repeatedly under the ciphertext and shifting each letter backward by the keyword letter's position decodes to 'the vault opens at noon'.",
    "incorrectExplanation": "This is a Vigenere cipher with the six-letter keyword SHADOW. Repeat it beneath the ciphertext and shift each letter backward by the keyword letter's alphabet position (A=0 ... Z=25)."
  },
  {
    "id": "cipher-machines-whisper",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Machine's Whisper",
    "question": "",
    "correctAnswer": "trust the code",
    "acceptedAnswers": [
      "trust the code"
    ],
    "xpReward": 130,
    "cipherData": {
      "encodedMessage": "01110100 01110010 01110101 01110011 01110100 00100000 01110100 01101000 01100101 00100000 01100011 01101111 01100100 01100101",
      "cipherType": "Binary",
      "hint": "The machine speaks only in nought and one. Gather its glyphs into groups of eight and read each octet as the character it names."
    },
    "correctExplanation": "Each group of 8 bits is one ASCII character. Converting every octet to its character spells 'trust the code' (the space is the byte 00100000).",
    "incorrectExplanation": "Split the digits into groups of 8. Read each group as a binary number, then map that number to its ASCII character. The group 00100000 is a space."
  },
  {
    "id": "cipher-gardeners-riddle",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Gardener's Riddle",
    "question": "",
    "correctAnswer": "a mountain",
    "acceptedAnswers": [
      "a mountain",
      "mountain"
    ],
    "xpReward": 150,
    "cipherData": {
      "encodedMessage": "23 8 1 20  8 1 19  18 15 15 20 19  14 15 2 15 4 25  19 5 5 19  1 14 4  9 19  20 1 12 12 5 18  20 8 1 14  20 18 5 5 19",
      "cipherType": "A1Z26 + Riddle",
      "hint": "Every integer is only its letter's rank in the alphabet; the twin gaps sever the words. What surfaces is an old riddle, and its answer is what you must name."
    },
    "correctExplanation": "Map each number to a letter (double spaces mark word breaks): the message decodes to 'what has roots nobody sees and is taller than trees'. The answer to that old riddle is a mountain.",
    "incorrectExplanation": "Convert the numbers to letters (1=A ... 26=Z, double spaces mark word breaks). That reveals a riddle. The final answer is the riddle's solution, a mountain, not the decoded line."
  },
  {
    "id": "cipher-twin-seal",
    "type": "cipher",
    "category": "puzzles",
    "difficulty": "hard",
    "title": "The Twin Seal",
    "question": "",
    "correctAnswer": "the serpent sleeps",
    "acceptedAnswers": [
      "the serpent sleeps"
    ],
    "xpReward": 160,
    "cipherData": {
      "encodedMessage": "dps esfhsjd elsshe",
      "cipherType": "Caesar + Atbash",
      "hint": "Two seals guard this door. The message was first slid three places along the alphabet, then reflected across its mirror. Undo the mirror first, for it is its own inverse, then slide three places back."
    },
    "correctExplanation": "Two layers: a Caesar shift of +3 followed by Atbash. Atbash is its own inverse, so mirror the alphabet first, then shift each letter back by 3 to recover 'the serpent sleeps'.",
    "incorrectExplanation": "This has two stages. Apply Atbash first (the alphabet mirrored onto itself), then undo a Caesar shift of 3 by moving each letter back three places. Order matters: mirror, then shift."
  }
];

export default cipherSeeds;
