import type { SeedData } from "./importer";

const seedData: SeedData = {
  lessonGroups: [
    // ===== LOGIC =====
    { category: "logic", name: "Think Straight", order: 1 },
    { category: "logic", name: "Spot the Pattern", order: 2 },
    { category: "logic", name: "Solve It", order: 3 },
    { category: "logic", name: "Master Mind", order: 4 },

    // ===== RIDDLES =====
    { category: "riddles", name: "Classic Riddles", order: 1 },
    { category: "riddles", name: "Funny Business", order: 2 },
    { category: "riddles", name: "Tricky Words", order: 3 },
    { category: "riddles", name: "Brain Busters", order: 4 },

    // ===== SCIENCE =====
    { category: "science", name: "Body & Biology", order: 1 },
    { category: "science", name: "Physics Fun", order: 2 },
    { category: "science", name: "Earth & Space", order: 3 },
    { category: "science", name: "Crazy Chemistry", order: 4 },
    { category: "science", name: "Science Mix", order: 5 },

    // ===== PUZZLES =====
    { category: "puzzles", name: "Number Crunch", order: 1 },
    { category: "puzzles", name: "Word Play", order: 2 },
    { category: "puzzles", name: "Think Different", order: 3 },
    { category: "puzzles", name: "Bonus Round", order: 4 },
  ],

  puzzles: [
    // ========================================================================
    // LOGIC — Group 1: Think Straight
    // ========================================================================
    {
      type: "true-false",
      category: "logic",
      difficulty: "easy",
      title: "True or False?",
      question: "All squares are rectangles, but not all rectangles are squares.",
      choices: ["True", "False"],
      correctAnswer: "True",
      xpReward: 10,
      lessonGroup: "Think Straight",
      lessonOrder: 1,
      lessonGroupOrder: 1,
      lessonContent:
        "Logic is the study of correct reasoning.\nA statement is either true or false — this is called the 'law of excluded middle'.\nIn logic, we build arguments from premises to reach a conclusion.\nA valid argument is one where if the premises are true, the conclusion must also be true.",
      correctExplanation: "Correct! A square has 4 equal sides (so it IS a rectangle), but a rectangle can have 2 long and 2 short sides (so not all rectangles are squares).",
      incorrectExplanation: "Actually this is true. A square meets all the requirements of a rectangle (4 right angles, opposite sides parallel), so it IS a rectangle, but rectangles don't need equal sides.",
    },
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "easy",
      title: "All A are B",
      question: "If all cats are mammals, and all mammals are warm-blooded, can we conclude that all cats are warm-blooded?",
      choices: ["Yes, this is valid", "No, this is a fallacy", "Only if cats are cute", "We need more information"],
      correctAnswer: "Yes, this is valid",
      xpReward: 10,
      lessonGroup: "Think Straight",
      lessonOrder: 2,
      lessonGroupOrder: 1,
      lessonContent:
        "A syllogism is a logical argument with two premises and a conclusion.\nIf A is a subset of B, and B is a subset of C, then A is a subset of C.\nThis is called 'transitive reasoning'.\nSpotting valid syllogisms helps you evaluate arguments in daily life.",
      correctExplanation: "Exactly! If all cats ⊆ mammals and mammals ⊆ warm-blooded, then cats ⊆ warm-blooded. This is a classic valid syllogism.",
      incorrectExplanation: "Actually this IS valid. It's a classic syllogism — if A is a subset of B and B is a subset of C, then A is a subset of C. Cats are a subset of mammals, which are a subset of warm-blooded creatures.",
    },
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "easy",
      title: "What Follows?",
      question: "If it is raining, then the ground is wet. The ground is wet. Does this mean it must have rained?",
      choices: ["Yes, definitely", "No, maybe something else wet it", "Only if it's cloudy", "The ground can't get wet"],
      correctAnswer: "No, maybe something else wet it",
      xpReward: 10,
      lessonGroup: "Think Straight",
      lessonOrder: 3,
      lessonGroupOrder: 1,
      lessonContent:
        "This is the 'fallacy of affirming the consequent' — just because Q follows from P, Q being true doesn't prove P.\nExample: 'If I study, I pass' + 'I passed' ≠ 'I studied' (I could have cheated!).\nTo correctly conclude P from Q, you need: 'If P then Q' and 'Not Q' → 'Not P' (modus tollens).\nUnderstanding these fallacies makes you a sharper thinker.",
      correctExplanation: "Right! The ground could be wet from a sprinkler, a spilled bucket, or someone washing their car. The statement 'if rain then wet ground' doesn't work backwards automatically.",
      incorrectExplanation: "Not quite — this is a classic logical fallacy called 'affirming the consequent'. The ground could be wet from a hose, a sprinkler, or anything else. We can't conclude it must have rained.",
    },
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "medium",
      title: "Logic Check",
      question: "Which of the following is a logical fallacy?",
      choices: [
        "Everyone I know believes the earth is round, so it must be round",
        "The earth is round because scientists have photographed it from space",
        "If the earth were flat, we would see the edge, and we don't",
        "Gravity pulls objects toward the center, creating a spherical shape",
      ],
      correctAnswer: "Everyone I know believes the earth is round, so it must be round",
      xpReward: 15,
      lessonGroup: "Think Straight",
      lessonOrder: 4,
      lessonGroupOrder: 1,
      lessonContent:
        "A logical fallacy is an error in reasoning that makes an argument invalid.\n'Argumentum ad populum' (appeal to popularity) — just because many people believe something doesn't make it true.\nOther common fallacies: ad hominem (attacking the person), straw man (misrepresenting the argument).\nLearning fallacies helps you spot weak arguments in debates, ads, and news.",
      correctExplanation: "Correct! 'Everyone believes it, so it must be true' is the 'appeal to popularity' fallacy. Popularity doesn't equal truth — at one point everyone believed the sun revolved around the earth.",
      incorrectExplanation: "The first option is the fallacy here. It's 'argumentum ad populum' — believing something because everyone else does. The other options are actual valid reasoning (empirical evidence, logical deduction, causal explanation).",
    },

    // ========================================================================
    // LOGIC — Group 2: Spot the Pattern
    // ========================================================================
    {
      type: "type-answer",
      category: "logic",
      difficulty: "easy",
      title: "Number Sequence",
      question: "What number comes next in this sequence?\n2, 4, 6, 8, ?",
      correctAnswer: "10",
      acceptedAnswers: ["10", "ten"],
      xpReward: 10,
      lessonGroup: "Spot the Pattern",
      lessonOrder: 1,
      lessonGroupOrder: 2,
      lessonContent:
        "Pattern recognition is a core logical skill.\nSequences can follow simple rules like 'add 2 each time'.\nReal-world patterns help us predict weather, stock markets, and even human behavior.\nAlways check: is the rule consistent for ALL terms in the sequence?",
      correctExplanation: "Yes! The pattern is +2 each time: 2→4 (+2), 4→6 (+2), 6→8 (+2), so next is 8+2=10.",
      incorrectExplanation: "The pattern is adding 2 each time. Starting from 2: +2=4, +2=6, +2=8, so the next is +2=10.",
    },
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "easy",
      title: "Odd One Out",
      question: "Which word is the odd one out?",
      choices: ["Triangle", "Square", "Circle", "Rectangle"],
      correctAnswer: "Circle",
      xpReward: 10,
      lessonGroup: "Spot the Pattern",
      lessonOrder: 2,
      lessonGroupOrder: 2,
      lessonContent:
        "Finding the 'odd one out' tests your ability to classify and categorize.\nLook for shared properties: number of sides, angles, curves, symmetry.\nSometimes the difference is subtle — functional vs. structural.\nThis skill translates directly to data analysis and scientific classification.",
      correctExplanation: "Right! Triangle, square, and rectangle all have straight sides/angles. A circle is curved with no angles or sides.",
      incorrectExplanation: "The circle is the odd one out. Triangle, square, and rectangle all have straight sides and angles. A circle is a continuous curve with no sides.",
    },
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "medium",
      title: "Complete the Pattern",
      question: "What comes next in this letter pattern?\nA, C, F, J, ?",
      choices: ["K", "L", "M", "O"],
      correctAnswer: "O",
      xpReward: 15,
      lessonGroup: "Spot the Pattern",
      lessonOrder: 3,
      lessonGroupOrder: 2,
      lessonContent:
        "Letter patterns work like number patterns — find the rule!\nSkip count: A→C is skip 1, C→F is skip 2, F→J is skip 3.\nSo the next skip is 4: J + 4 letters = N... wait, let me count.\nAlways double-check your pattern against ALL given terms before answering.",
      correctExplanation: "Correct! A→C (+2), C→F (+3), F→J (+4), so next is J→? (+5). The 5th letter after J is O (J, K, L, M, N, O — that's +5, so O).",
      incorrectExplanation: "The pattern increases the skip by 1 each time: A→C (skip 1), C→F (skip 2), F→J (skip 3), so J→? needs skip 4 → O.",
    },
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "medium",
      title: "Shape Logic",
      question: "If ★ = 5 and ● = 3, what does ★ + ● × 2 equal?",
      choices: ["11", "16", "13", "10"],
      correctAnswer: "11",
      xpReward: 15,
      lessonGroup: "Spot the Pattern",
      lessonOrder: 4,
      lessonGroupOrder: 2,
      lessonContent:
        "Follow order of operations: Multiplication and division come BEFORE addition and subtraction.\nPEMDAS / BODMAS: Parentheses, Exponents, Multiplication, Division, Addition, Subtraction.\nThis puzzle tests both symbol substitution and operation precedence.\nMany people get this wrong by adding before multiplying!",
      correctExplanation: "Correct! Order of operations says multiplication first: ● × 2 = 3 × 2 = 6, then ★ + 6 = 5 + 6 = 11.",
      incorrectExplanation: "Remember PEMDAS! Multiplication before addition: ● × 2 = 3 × 2 = 6. Then ★ + 6 = 5 + 6 = 11. The common mistake is adding first: 5+3=8, then ×2=16 — that's wrong.",
    },

    // ========================================================================
    // LOGIC — Group 3: Solve It
    // ========================================================================
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "medium",
      title: "River Crossing",
      question: "A farmer needs to cross a river with a wolf, a goat, and a cabbage. His boat can only carry him and one item at a time. If left alone, the wolf eats the goat, and the goat eats the cabbage. How many trips minimum does the farmer need to make (one-way trips, including the final crossing)?",
      choices: ["5 trips", "7 trips", "9 trips", "4 trips"],
      correctAnswer: "7 trips",
      xpReward: 20,
      lessonGroup: "Solve It",
      lessonOrder: 1,
      lessonGroupOrder: 3,
      lessonContent:
        "The river crossing puzzle is over 1,000 years old — first recorded in 8th-century Europe.\nIt's a classic 'state space search' problem used in AI planning.\nThe key insight: sometimes you need to bring something BACK across to solve it.\nThis teaches the concept of 'subgoal decomposition' in problem-solving.",
      correctExplanation: "Right! The solution: ① Take goat across ② Return alone ③ Take wolf across ④ Bring goat BACK ⑤ Take cabbage across ⑥ Return alone ⑦ Take goat across. That's 7 one-way trips.",
      incorrectExplanation: "The solution needs 7 trips: Goat→, ←, Wolf→, Goat←, Cabbage→, ←, Goat→. You must bring the goat back on trip 4 to avoid leaving it with the cabbage.",
    },
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "medium",
      title: "Truth Tellers",
      question: "You meet two people at a fork in the road. One always tells the truth, one always lies. One path leads to treasure, the other to danger. You can ask ONE question to ONE person. What do you ask to find the treasure?",
      choices: [
        "Which path leads to treasure?",
        "What would the other person say leads to treasure?",
        "Are you the truth-teller?",
        "Is this the path to treasure?",
      ],
      correctAnswer: "What would the other person say leads to treasure?",
      xpReward: 25,
      lessonGroup: "Solve It",
      lessonOrder: 2,
      lessonGroupOrder: 3,
      lessonContent:
        "The 'knights and knaves' puzzle was popularized by logician Raymond Smullyan.\nThe trick: a truth-teller and a liar will give the SAME wrong answer about what the other would say.\nThis is because: truth-teller reports the liar's lie (false), liar lies about what truth-teller would say (also false).\nYou then take the OPPOSITE path to what they say.",
      correctExplanation: "Correct! Both will point to the wrong path. The truth-teller will honestly say what the liar would say (wrong path), and the liar will lie about what the truth-teller would say (also wrong path). Take the opposite.",
      incorrectExplanation: "The clever trick: ask 'What would the other say?' Both will point to the WRONG path. The truth-teller reports the liar's lie (wrong), the liar lies about the truth-teller's answer (also wrong). Take the opposite path.",
    },
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "hard",
      title: "The Missing Dollar",
      question: "Three friends pay $30 for a hotel room ($10 each). Later the clerk realizes the room is only $25, so gives $5 to the bellboy to return. The bellboy keeps $2 and gives $1 back to each friend. Now each friend paid $9 ($27 total) plus the bellboy's $2 = $29. Where is the missing dollar?",
      choices: [
        "There is no missing dollar — the logic is flawed",
        "The bellboy stole it",
        "The hotel has it",
        "The friends miscounted",
      ],
      correctAnswer: "There is no missing dollar — the logic is flawed",
      xpReward: 25,
      lessonGroup: "Solve It",
      lessonOrder: 3,
      lessonGroupOrder: 3,
      lessonContent:
        "This puzzle tricks you with irrelevant arithmetic.\nThe correct math: $25 (hotel) + $2 (bellboy) + $3 (refund) = $30.\nThe error: adding $27 (what friends paid) + $2 (bellboy's portion) is double-counting.\nThe $2 is already INCLUDED in the $27 ($25 hotel + $2 bellboy).",
      correctExplanation: "Exactly! The puzzle misdirects you. The $27 already includes the bellboy's $2. The proper accounting is $25 (hotel) + $2 (bellboy) + $3 (refund) = $30. There's no missing dollar.",
      incorrectExplanation: "The trick is in how the numbers are added. The friends paid $27 ($25 for the room + $2 to the bellboy). Adding the bellboy's $2 again is wrong. Correct: $25 (room) + $2 (bellboy) + $3 (refund) = $30.",
    },
    {
      type: "type-answer",
      category: "logic",
      difficulty: "hard",
      title: "Clock Puzzle",
      question: "How many times do the hour and minute hands of a clock overlap in a 12-hour period?",
      correctAnswer: "11",
      acceptedAnswers: ["11", "eleven"],
      xpReward: 25,
      lessonGroup: "Solve It",
      lessonOrder: 4,
      lessonGroupOrder: 3,
      lessonContent:
        "The hands overlap once per hour, but NOT 12 times!\nBetween 12:00 and 1:00, they overlap ONLY at 12:00 (start).\nThe overlaps happen at roughly 1:05, 2:10, 3:16, etc.\nSo in 12 hours: 12 - 1 = 11 overlaps. The 12th overlap is at the next 12:00, which starts the next cycle.",
      correctExplanation: "Yes! The hands overlap 11 times in 12 hours. They don't overlap between 12 and 1 (after 12:00, the next overlap is around 1:05). Count: the 12:00 overlap starts the period, then 1:05, 2:10... up to 10:55 = 11 total.",
      incorrectExplanation: "The answer is 11, not 12. The hands don't overlap between 12:00 and 1:00 (they only overlap at exactly 12:00 which starts the period). So over 12 hours: 12:00, 1:05, 2:10, 3:16, 4:22, 5:27, 6:33, 7:38, 8:44, 9:49, 10:55 = 11 times.",
    },

    // ========================================================================
    // LOGIC — Group 4: Master Mind
    // ========================================================================
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "hard",
      title: "Einstein's Puzzle",
      question: "Five houses in a row, each a different color, owned by people of different nationalities who drink different drinks, smoke different brands, and keep different pets. The Brit lives in the red house. The Swede keeps dogs. The Dane drinks tea. The green house is left of the white house (adjacent). The green house owner drinks coffee. The person who smokes Pall Mall rears birds. The owner of the yellow house smokes Dunhill. The man living in the center house drinks milk. The Norwegian lives in the first house. The man who smokes Blends lives next to the one who keeps cats. The man who keeps horses lives next to the man who smokes Dunhill. The man who smokes Blue Master drinks beer. The German smokes Prince. The Norwegian lives next to the blue house. The man who smokes Blends has a neighbor who drinks water. Who owns the fish?",
      choices: ["Brit", "Swede", "Dane", "German"],
      correctAnswer: "German",
      xpReward: 30,
      lessonGroup: "Master Mind",
      lessonOrder: 1,
      lessonGroupOrder: 4,
      lessonContent:
        "This is often called 'Einstein's Riddle' — Einstein supposedly created it as a boy.\nGrid logic puzzles use a systematic elimination approach.\nStart with what you KNOW, fill in what follows, and keep iterating.\nPro tip: draw a 5×5 grid with categories (house, color, nationality, drink, smoke, pet) and use X's and checks.",
      correctExplanation: "Impressive! After systematically applying all 15 clues, the German is the only one left for the fish. The complete arrangement: Yellow (Norwegian, water, Dunhill, cats), Blue (Dane, tea, Blends, horses), Red (Brit, milk, Pall Mall, birds), Green (German, coffee, Prince, FISH), White (Swede, beer, Blue Master, dogs).",
      incorrectExplanation: "Work through the clues systematically. Using a grid: The Norwegian is in house 1 (blue? no, clue 14 says Norwegian lives next to blue, so house 2 is blue)... The German drinks coffee, smokes Prince, and after full deduction ends up in the green house with the fish.",
    },
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "hard",
      title: "The Hardest Logic Puzzle",
      question: "Three gods: A (always truth), B (always lie), C (random). You can ask three yes/no questions, each to any god. They answer in their language — 'da' means yes or no (you don't know which). How do you find out which god is which?",
      choices: [
        "It's impossible with only 3 questions",
        "Ask 'If I asked you Q, would you say da?'",
        "Ask each god directly who they are",
        "Ask about the other gods' identities",
      ],
      correctAnswer: "Ask 'If I asked you Q, would you say da?'",
      xpReward: 30,
      lessonGroup: "Master Mind",
      lessonOrder: 2,
      lessonGroupOrder: 4,
      lessonContent:
        "This puzzle was created by philosopher George Boolos in 1996.\nThe trick: 'If I asked you Q, would you say da?' normalizes the answer.\nRegardless of whether da=yes or da=no, a truth-teller answers da exactly when Q is true.\nA liar ALSO answers da when Q is true (because they'd lie about what they'd say).",
      correctExplanation: "Correct! The embedded question trick works because: for truth-teller, if Q is true they say da (would answer da), if false they say 'no' (wouldn't). For liar, they'd lie about what they'd say, which flips twice and gives the same result. Complex but brilliant!",
      incorrectExplanation: "The trick uses an embedded question: 'If I asked Q, would you say da?' This normalizes the meaning of 'da' — both truth-teller and liar will answer da exactly when the answer to Q is yes, regardless of what 'da' actually means.",
    },
    {
      type: "type-answer",
      category: "logic",
      difficulty: "hard",
      title: "Code Breaker",
      question: "Decode the pattern:\n1234 = 0\n5678 = 3\n9012 = 2\n3456 = 1\n7890 = 4\nWhat does 2468 = ?",
      correctAnswer: "3",
      acceptedAnswers: ["3", "three"],
      xpReward: 30,
      lessonGroup: "Master Mind",
      lessonOrder: 3,
      lessonGroupOrder: 4,
      lessonContent:
        "This puzzle tricks you into looking for complex math patterns.\nThe answer has nothing to do with the numbers' values!\nHint: Look at the digits themselves — what do they contain?\nThe answer is the count of 'closed loops' in each digit.",
      correctExplanation: "Correct! The value equals the number of closed loops in each digit: 0 has 1 loop, 6 has 1, 8 has 2, 9 has 1. All other digits have 0 loops. So 2468 = 0 (2) + 0 (4) + 1 (6) + 2 (8) = 3.",
      incorrectExplanation: "Count closed loops in each digit: 2→0, 4→0, 6→1, 8→2. Total = 0+0+1+2 = 3. It's a visual pattern, not a math problem!",
    },
    {
      type: "multiple-choice",
      category: "logic",
      difficulty: "hard",
      title: "Ultimate Challenge",
      question: "A bookshelf has three volumes of an encyclopedia side by side: Volume I, II, III (left to right). Each volume is 4cm thick (covers) and the pages are 3cm thick. A bookworm starts at page 1 of Volume I and eats straight through to the last page of Volume III. How far does it travel?",
      choices: ["7 cm", "10 cm", "17 cm", "3 cm"],
      correctAnswer: "3 cm",
      xpReward: 30,
      lessonGroup: "Master Mind",
      lessonOrder: 4,
      lessonGroupOrder: 4,
      lessonContent:
        "This puzzle tests your ability to visualize — don't just do math!\nVolume I is on the LEFT. Page 1 of Volume I is on the RIGHT side of Volume I (books are shelved with page 1 on the right).\nLast page of Volume III is on the LEFT side of Volume III.\nSo the bookworm only travels through Volume II (between the right cover of I and left cover of III).",
      correctExplanation: "Correct! The trick: Volume I is on the left. Page 1 is on the RIGHT side of Volume I. The last page of Volume III is on the LEFT side of Volume III. So the bookworm only passes through the pages of Volume II (3cm). Not through Volume I or III covers at all!",
      incorrectExplanation: "Picture the books: Volume I (left) has page 1 on its RIGHT side. Volume III (right) has last page on its LEFT side. The bookworm starts at Vol I's right edge and ends at Vol III's left edge — it only traverses Volume II's 3cm of pages.",
    },

    // ========================================================================
    // RIDDLES — Group 1: Classic Riddles
    // ========================================================================
    {
      type: "riddle",
      category: "riddles",
      difficulty: "easy",
      title: "The Sphinx's Riddle",
      question: "I walk on four legs in the morning, two legs at noon, and three legs in the evening. What am I?",
      correctAnswer: "Human",
      acceptedAnswers: ["Human", "A human", "Person", "A person", "Man", "Woman"],
      xpReward: 10,
      hintText: "Think about the stages of life, not actual legs.\n'Morning', 'noon', and 'evening' represent childhood, adulthood, and old age.",
      lessonGroup: "Classic Riddles",
      lessonOrder: 1,
      lessonGroupOrder: 1,
      lessonContent:
        "This is the most famous riddle in history — from the Greek myth of Oedipus and the Sphinx.\nThe Sphinx guarded the gates of Thebes and devoured anyone who couldn't solve it.\nOedipus solved it, causing the Sphinx to destroy herself.\nThe answer describes the human lifespan through metaphor.",
      correctExplanation: "Yes! A human crawls as a baby (4 legs), walks upright as an adult (2 legs), and uses a cane in old age (3 legs).",
      incorrectExplanation: "The answer is a human. 'Morning' = infancy (crawling on all fours), 'Noon' = adulthood (walking on two legs), 'Evening' = old age (walking with a cane).",
    },
    {
      type: "riddle",
      category: "riddles",
      difficulty: "easy",
      title: "I Speak Without a Mouth",
      question: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?",
      correctAnswer: "Echo",
      acceptedAnswers: ["Echo", "An echo"],
      xpReward: 10,
      hintText: "Think about what happens when sound bounces off a surface.\nIt's the reflection of sound waves.",
      lessonGroup: "Classic Riddles",
      lessonOrder: 2,
      lessonGroupOrder: 1,
      lessonContent:
        "An echo is the reflection of sound waves off a surface.\nSound travels at roughly 343 meters per second in air.\nYou need at least 17 meters distance to hear a distinct echo (your ear can distinguish sounds 0.1 seconds apart).\nThe word 'echo' comes from Greek mythology — Echo was a nymph who could only repeat others' words.",
      correctExplanation: "Yes! An echo 'speaks' (repeats sound) without a mouth, 'hears' without ears, and needs wind (air to carry sound) but has no body.",
      incorrectExplanation: "It's an echo! Sound bounces off distant surfaces and returns to you. The echo seems to 'speak' by repeating what you said, but it has no mouth, ears, or body.",
    },
    {
      type: "riddle",
      category: "riddles",
      difficulty: "easy",
      title: "The More You Take",
      question: "The more you take, the more you leave behind. What am I?",
      correctAnswer: "Footsteps",
      acceptedAnswers: ["Footsteps", "Footsteps/Steps", "Steps", "A footstep"],
      xpReward: 10,
      hintText: "Think about movement and what you leave behind as you walk.\nIt's not a physical object you hold.",
      lessonGroup: "Classic Riddles",
      lessonOrder: 3,
      lessonGroupOrder: 1,
      lessonContent:
        "This is one of the oldest known English riddles, dating back centuries.\nIt plays on the double meaning of 'take' — taking a step vs. taking an object.\nThe more steps you 'take', the more footprints (footsteps) you leave behind.\nSimple but clever wordplay is the hallmark of great riddles.",
      correctExplanation: "Correct! Every step you 'take' leaves a footprint behind. The more steps you take, the more footsteps trail behind you.",
      incorrectExplanation: "The answer is footsteps. Each step you 'take' leaves a footprint behind. So the more steps you take, the more footsteps you've left behind you.",
    },
    {
      type: "riddle",
      category: "riddles",
      difficulty: "easy",
      title: "I Have Cities",
      question: "I have cities, but no houses. I have forests, but no trees. I have rivers, but no water. What am I?",
      correctAnswer: "A map",
      acceptedAnswers: ["A map", "Map"],
      xpReward: 10,
      hintText: "Think about something that represents real things without being those things.\nIt's flat and usually folded.",
      lessonGroup: "Classic Riddles",
      lessonOrder: 4,
      lessonGroupOrder: 1,
      lessonContent:
        "A map is a symbolic representation of geographical features.\nMaps date back over 8,000 years — the oldest known map is a Babylonian clay tablet.\nModern maps use symbols: dots for cities, green for forests, blue lines for rivers.\nThe riddle works because maps SHOW these features but don't contain the actual things.",
      correctExplanation: "Yes! A map shows cities, forests, and rivers as symbols, but doesn't contain actual houses, trees, or water — just paper and ink.",
      incorrectExplanation: "It's a map. Maps represent real places with symbols — cities are dots (not actual houses), forests are colored areas (not real trees), rivers are lines (not actual water).",
    },

    // ========================================================================
    // RIDDLES — Group 2: Funny Business
    // ========================================================================
    {
      type: "riddle",
      category: "riddles",
      difficulty: "easy",
      title: "Fake Noodle",
      question: "What do you call a fake noodle?",
      correctAnswer: "An impasta",
      acceptedAnswers: ["An impasta", "Impasta", "Im-pasta", "An im-pasta"],
      xpReward: 10,
      hintText: "It's a pun — think 'imposter' but with pasta.\nSay it out loud: 'im-pasta'.",
      lessonGroup: "Funny Business",
      lessonOrder: 1,
      lessonGroupOrder: 2,
      lessonContent:
        "Puns are a form of wordplay that exploit multiple meanings of words.\nThey're considered the lowest form of humor AND the highest form of wit (depending on who you ask).\nShakespeare used over 3,000 puns in his plays.\nA good pun gives you a moment of confusion followed by an 'aha!' groan.",
      correctExplanation: "Haha, yes! 'Impasta' sounds like 'imposter' — a fake person, but with pasta instead! Pun-ishingly good.",
      incorrectExplanation: "It's an 'impasta' — a pun on 'imposter' (a fake/fraud) mixed with 'pasta' (noodles). The joke is you expect 'impostor' but get a pasta-themed word instead!",
    },
    {
      type: "riddle",
      category: "riddles",
      difficulty: "easy",
      title: "The Scarecrow",
      question: "Why did the scarecrow win an award?",
      correctAnswer: "Because he was outstanding in his field",
      acceptedAnswers: [
        "He was outstanding in his field",
        "Outstanding in his field",
        "Because he was outstanding",
      ],
      xpReward: 10,
      hintText: "Think about what a scarecrow does for a living — and what 'outstanding' can mean.\nIt's a double meaning joke.",
      lessonGroup: "Funny Business",
      lessonOrder: 2,
      lessonGroupOrder: 2,
      lessonContent:
        "This is a classic 'double meaning' joke.\n'Outstanding' can mean excellent/noteworthy, OR literally 'standing out' in a field.\nScarecrows literally stand out in fields to scare birds.\nThe humor comes from the unexpected second meaning.",
      correctExplanation: "Yes! 'Outstanding' has two meanings: (1) exceptionally good, and (2) literally standing outside in a field. The scarecrow qualifies for both!",
      incorrectExplanation: "Because he was 'outstanding in his field' — he's a scarecrow who stands in a field (literal), and 'outstanding' also means excellent (figurative). The pun works both ways!",
    },
    {
      type: "riddle",
      category: "riddles",
      difficulty: "easy",
      title: "Orange Parrot",
      question: "What's orange and sounds like a parrot?",
      correctAnswer: "A carrot",
      acceptedAnswers: ["A carrot", "Carrot"],
      xpReward: 10,
      hintText: "Say the answer out loud — it should sound like 'parrot' but starts with a 'c'.\nIt's a vegetable.",
      lessonGroup: "Funny Business",
      lessonOrder: 3,
      lessonGroupOrder: 2,
      lessonContent:
        "This is a simple pun based on similar pronunciation.\n'Carrot' and 'parrot' sound almost identical except for the first letter.\nIt's an 'equal pun' — both parts of the setup (color and sound) match equally.\nThe simplicity is what makes it funny — you feel silly for not getting it immediately.",
      correctExplanation: "Correct! A carrot is orange and 'carrot' sounds like 'parrot'. Simple but effective pun!",
      incorrectExplanation: "A carrot! It's orange in color and 'carrot' sounds very similar to 'parrot'. The joke tricks you into thinking of a bird when the answer is a vegetable.",
    },
    {
      type: "riddle",
      category: "riddles",
      difficulty: "easy",
      title: "The Door",
      question: "Knock knock.\nWho's there?\nLettuce.\nLettuce who?\nLettuce in, it's cold out here!",
      correctAnswer: "Lettuce",
      acceptedAnswers: ["Lettuce", "lettuce"],
      xpReward: 10,
      hintText: "What word sounds like 'let us' but is a vegetable?\nIt's green and leafy.",
      lessonGroup: "Funny Business",
      lessonOrder: 4,
      lessonGroupOrder: 2,
      lessonContent:
        "Knock-knock jokes follow a strict 5-line format.\nThe humor relies on the pun in the final punchline.\n'Lettuce' sounds like 'let us' — a plea to be allowed inside.\nKnock-knock jokes date back to Shakespeare's time (in 'Macbeth', the porter scene has a knock-knock-like pattern).",
      correctExplanation: "Correct! 'Lettuce' sounds like 'let us', so 'Lettuce in' is a pun for 'let us in'. A classic groaner!",
      incorrectExplanation: "The answer is 'lettuce' — it's a pun on 'let us'. The joke: Lettuce who? Lettuce (let us) in, it's cold out here!",
    },

    // ========================================================================
    // RIDDLES — Group 3: Tricky Words
    // ========================================================================
    {
      type: "type-answer",
      category: "riddles",
      difficulty: "medium",
      title: "Word Ladder",
      question: "Change one letter at a time:\nCAT → ? → DOG\nWhat's the middle word?",
      correctAnswer: "COT",
      acceptedAnswers: ["COT", "Cog", "cog"],
      xpReward: 15,
      hintText: "You need a valid 3-letter word in between.\nCAT to ? (change one letter) → ? to DOG (change one letter).\nTry changing the vowel first.",
      lessonGroup: "Tricky Words",
      lessonOrder: 1,
      lessonGroupOrder: 3,
      lessonContent:
        "Word Ladders were invented by Lewis Carroll (author of Alice in Wonderland) in 1877.\nAlso called 'doublets', they transform one word into another by changing one letter at a time.\nEach intermediate step must be a valid word.\nThe game was first published in Vanity Fair magazine.",
      correctExplanation: "Yes! CAT → C**O**T (change A to O) → **D**OT or C**O**T → **D**OG... actually CAT → COT (change A to O) → COG (change T to G) → DOG (change C to D). So either COT or COG works!",
      incorrectExplanation: "Possible answers: CAT → COT → DOG (change A→O, then C→D) or CAT → COG → DOG. Both work since each step changes exactly one letter to make a valid word.",
    },
    {
      type: "riddle",
      category: "riddles",
      difficulty: "medium",
      title: "Wrong Spelling",
      question: "What word is always spelled wrong?",
      correctAnswer: "Wrong",
      acceptedAnswers: ["Wrong", "The word 'wrong'"],
      xpReward: 15,
      hintText: "Think about the riddle itself. It says 'What word is always spelled wrong?' — that's a clue.\nThe answer is the word in the question!",
      lessonGroup: "Tricky Words",
      lessonOrder: 2,
      lessonGroupOrder: 3,
      lessonContent:
        "This is a self-referential riddle — it refers to itself.\nSelf-reference creates paradoxes: 'This statement is false'.\nThe word in the question that's 'always spelled wrong' is literally 'wrong'.\nBut wait... 'wrong' IS spelled correctly here! The paradox is part of the fun.",
      correctExplanation: "Yes! The word 'wrong' is always spelled W-R-O-N-G. So it's 'always spelled wrong' — meaning the word 'wrong' spells 'wrong'. Meta!",
      incorrectExplanation: "The answer is 'wrong' — the word itself. The question says 'what word is always spelled wrong?' and the answer is the word 'wrong' (which IS spelled correctly, creating the playful paradox).",
    },
    {
      type: "type-answer",
      category: "riddles",
      difficulty: "medium",
      title: "Anagram Time",
      question: "Rearrange the letters of 'LISTEN' to make another word. What is it?",
      correctAnswer: "SILENT",
      acceptedAnswers: ["SILENT", "silent", "Inlets", "inlets"],
      xpReward: 15,
      hintText: "All the same letters, just rearranged.\nThink of the opposite of making noise.\n'Netsil' is not a word!",
      lessonGroup: "Tricky Words",
      lessonOrder: 3,
      lessonGroupOrder: 3,
      lessonContent:
        "An anagram rearranges letters of a word or phrase to form another word.\n'Listen' and 'silent' use the exact same 6 letters.\nOther anagrams: 'astronomer' → 'moon starer', 'debit card' → 'bad credit'.\nAnagrams were considered a mystical art in ancient Greece and Rome.",
      correctExplanation: "Yes! L-I-S-T-E-N rearranged is S-I-L-E-N-T. Both use the same letters — a perfect anagram!",
      incorrectExplanation: "The answer is 'silent'. Listen → Silent. Both use the same 6 letters: E, I, L, N, S, T. Or 'inlets' is also valid!",
    },
    {
      type: "multiple-choice",
      category: "riddles",
      difficulty: "medium",
      title: "Double Meaning",
      question: "Which word means both 'a type of tree' and 'to depart'?",
      choices: ["Pine", "Leave", "Birch", "Oak"],
      correctAnswer: "Pine",
      xpReward: 15,
      lessonGroup: "Tricky Words",
      lessonOrder: 4,
      lessonGroupOrder: 3,
      lessonContent:
        "Words with multiple meanings are called 'homonyms' or 'polysemous words'.\n'Pine' can mean: a coniferous tree, OR to yearn/languish (as in 'I pine for you').\nEnglish is full of such words: 'bank' (river/money), 'bat' (animal/sports), 'seal' (animal/stamp).\nAbout 40% of English words have multiple meanings!",
      correctExplanation: "Correct! 'Pine' is both an evergreen tree and a verb meaning 'to yearn or miss someone deeply' (e.g., 'I pine for my homeland').",
      incorrectExplanation: "'Pine' is the answer. A pine is a type of tree, and 'to pine' means to yearn or miss someone. 'Leave' means to depart but is not a tree. 'Birch' is a tree but not a verb for departing.",
    },

    // ========================================================================
    // RIDDLES — Group 4: Brain Busters
    // ========================================================================
    {
      type: "riddle",
      category: "riddles",
      difficulty: "hard",
      title: "The Man in the Elevator",
      question: "A man lives on the 10th floor of a building. Every day he takes the elevator down to the ground floor to go to work. When he returns in the evening, he takes the elevator to the 7th floor and walks up the remaining 3 flights of stairs. Why?",
      correctAnswer: "He's too short to reach the button for floor 10",
      acceptedAnswers: [
        "He's too short to reach the 10th floor button",
        "He's a dwarf",
        "He's too short",
        "He can't reach the 10th floor button",
        "He is short",
        "Too short to reach the button",
      ],
      xpReward: 25,
      hintText: "Focus on the CONTROLS inside the elevator.\nWhy can he press 1 (ground) but not 10?\nThink about height and reach.",
      lessonGroup: "Brain Busters",
      lessonOrder: 1,
      lessonGroupOrder: 4,
      lessonContent:
        "This is a famous 'lateral thinking' puzzle.\nThe key: he can reach the ground floor button (it's near the bottom), but not the 10th floor button (too high).\nHe can reach the 7th floor button, so he goes to 7 and walks the rest.\nThe answer seems obvious once you know it — that's the hallmark of a great lateral puzzle!",
      correctExplanation: "Correct! He's a short person (a dwarf) who can only reach buttons up to the 7th floor. In the morning, he presses 1 (ground, bottom row). In the evening, he presses 7 (highest he can reach) and walks up 3 flights.",
      incorrectExplanation: "He's too short to reach the 10th floor button! He can press the ground floor button (1, bottom row) to go down, but coming back up, he can only reach up to 7. So he goes to 7 and takes the stairs the rest of the way.",
    },
    {
      type: "riddle",
      category: "riddles",
      difficulty: "hard",
      title: "The Barber Paradox",
      question: "A town has one barber who shaves all men who do not shave themselves, and ONLY those men. Who shaves the barber?",
      correctAnswer: "Nobody",
      acceptedAnswers: [
        "Nobody",
        "No one",
        "No one can",
        "It's a paradox",
        "The barber doesn't shave",
        "He doesn't shave",
      ],
      xpReward: 25,
      hintText: "If the barber shaves himself, then he's shaving a man who shaves himself (which he shouldn't).\nIf he doesn't shave himself, then he's a man who doesn't shave himself (which he should).\nEither way, it breaks the rule!",
      lessonGroup: "Brain Busters",
      lessonOrder: 2,
      lessonGroupOrder: 4,
      lessonContent:
        "Bertrand Russell created this paradox in 1901 to expose a flaw in set theory.\nIt's the same as: 'Does the set of all sets that don't contain themselves contain itself?'\nIf yes → it contains itself, so it shouldn't be in the set.\nIf no → it should be in the set. This broke Frege's entire logical system!",
      correctExplanation: "Exactly! It's a paradox. If the barber shaves himself, he's shaving someone who shaves himself (against the rule). If someone else shaves him, he doesn't shave himself (but then the barber should shave him). Impossible!",
      incorrectExplanation: "Nobody can shave the barber without breaking the rule. This is Russell's Paradox — the barber both must and cannot shave himself. The only resolution: the barber doesn't shave (bald?) or the paradox is inherent in the premise.",
    },
    {
      type: "riddle",
      category: "riddles",
      difficulty: "hard",
      title: "Two Doors, Two Guards",
      question: "You stand before two doors. One leads to certain death, the other to freedom. Two guards guard the doors — one always tells the truth, one always lies. You may ask ONE question to ONE guard. What do you ask?",
      correctAnswer: "If I asked the other guard which door leads to freedom, what would they say?",
      acceptedAnswers: [
        "Which door would the other guard say leads to freedom",
        "What would the other guard say",
        "Ask what the other would say",
        "If I asked the other guard which door is safe, what would they answer",
      ],
      xpReward: 25,
      hintText: "Think about how both guards will answer the same way.\nThe truth-teller will honestly report the liar's lie.\nThe liar will lie about what the truth-teller would say.\nBoth will point to the WRONG door!",
      lessonGroup: "Brain Busters",
      lessonOrder: 3,
      lessonGroupOrder: 4,
      lessonContent:
        "This is a harder version of the truth-teller/liar puzzle.\nThe key: embed a question about 'what the OTHER would say'.\nBoth guards point to the SAME door — the WRONG one.\nYou then choose the OTHER door. This works because a double-negative equals a negative!",
      correctExplanation: "Correct! Ask either guard: 'What would the other guard say leads to freedom?' Both will point to the DEATH door. The truth-teller reports the liar's lie (wrong), the liar lies about the truth-teller's answer (also wrong). Take the other door!",
      incorrectExplanation: "Ask 'Which door would the other guard point to?' Both will point to the death door. The truth-teller truthfully says the liar's wrong answer. The liar lies about the truth-teller's correct answer. Both give the wrong door — so choose the opposite.",
    },
    {
      type: "riddle",
      category: "riddles",
      difficulty: "hard",
      title: "What Am I?",
      question: "I am taken from a mine and shut up in a wooden case, from which I am never released. What am I?",
      correctAnswer: "Pencil lead",
      acceptedAnswers: [
        "Pencil lead",
        "Graphite",
        "A pencil",
        "Pencil",
        "Pencil lead (graphite)",
      ],
      xpReward: 25,
      hintText: "What's inside a pencil that comes from mining?\nIt's not actual lead — it's a form of carbon.\nThe 'wooden case' is the pencil body.",
      lessonGroup: "Brain Busters",
      lessonOrder: 4,
      lessonGroupOrder: 4,
      lessonContent:
        "This riddle by J.R.R. Tolkien (yes, The Hobbit/Lord of the Rings author!) is a classic.\nPencil 'lead' is actually graphite — a form of carbon.\nIt's 'mined' from the ground, then 'shut up in wood' (the pencil).\nIt's 'never released' because you use it until the pencil is gone — the lead is consumed, never freed!",
      correctExplanation: "Yes! Pencil lead (graphite) is mined, encased in wood, and is gradually used up — never 'released' from its wooden prison. A brilliant riddle by J.R.R. Tolkien!",
      incorrectExplanation: "The answer is pencil lead/graphite. It's mined from the earth, enclosed in a wooden pencil case, and as you write with it, it wears away — it's never 'released' from the wood.",
    },

    // ========================================================================
    // SCIENCE — Group 1: Body & Biology
    // ========================================================================
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "easy",
      title: "The Human Engine",
      question: "What is the largest organ in the human body?",
      choices: ["Liver", "Brain", "Skin", "Heart"],
      correctAnswer: "Skin",
      xpReward: 10,
      lessonGroup: "Body & Biology",
      lessonOrder: 1,
      lessonGroupOrder: 1,
      lessonContent:
        "Your skin is your body's largest organ, weighing about 8-10 pounds (3.5-4.5 kg).\nIt covers about 22 square feet (2 sq meters) in an average adult.\nSkin has three layers: epidermis, dermis, and hypodermis.\nIt protects against germs, regulates temperature, and lets you feel touch.",
      correctExplanation: "Correct! Your skin is the largest organ — about 22 square feet! The liver is the largest internal organ, but skin is the overall largest.",
      incorrectExplanation: "The skin is the largest organ! It covers your entire body and weighs about 8-10 pounds. The liver is the largest internal organ (about 3 pounds), but skin is bigger.",
    },
    {
      type: "true-false",
      category: "science",
      difficulty: "easy",
      title: "Animal Kingdom",
      question: "A group of flamingos is called a 'flamboyance'.",
      choices: ["True", "False"],
      correctAnswer: "True",
      xpReward: 10,
      lessonGroup: "Body & Biology",
      lessonOrder: 2,
      lessonGroupOrder: 1,
      lessonContent:
        "Animal group names are wonderfully creative!\nA group of flamingos is indeed a 'flamboyance' — fitting for such colorful birds.\nOther fun ones: a 'murder' of crows, a 'parliament' of owls, a 'crash' of rhinos.\nFlamingos get their pink color from their diet of shrimp and algae.",
      correctExplanation: "True! A group of flamingos is called a flamboyance. Perfect name for such flashy pink birds!",
      incorrectExplanation: "It's true! A group of flamingos is called a 'flamboyance'. Other great group names: a 'conspiracy' of lemurs, an 'embarrassment' of pandas, and a 'shrewdness' of apes.",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "easy",
      title: "Plant Power",
      question: "What gas do plants absorb from the atmosphere during photosynthesis?",
      choices: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"],
      correctAnswer: "Carbon dioxide",
      xpReward: 10,
      lessonGroup: "Body & Biology",
      lessonOrder: 3,
      lessonGroupOrder: 1,
      lessonContent:
        "Photosynthesis: 6CO₂ + 6H₂O + sunlight → C₆H₁₂O₆ (glucose) + 6O₂.\nPlants absorb carbon dioxide and water, using sunlight to make food (sugar).\nOxygen is the waste product — which we breathe!\nThis is why trees are called 'the lungs of the Earth'.",
      correctExplanation: "Yes! Plants absorb carbon dioxide and release oxygen during photosynthesis. The carbon becomes part of the glucose (sugar) the plant uses for energy.",
      incorrectExplanation: "Plants absorb carbon dioxide (CO₂). During photosynthesis, they combine CO₂ + water + sunlight to make sugar + oxygen. That's why forests are so important — they convert our CO₂ waste into breathable oxygen.",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "medium",
      title: "DNA Detective",
      question: "What shape is a DNA molecule?",
      choices: ["Straight ladder", "Double helix", "Single strand", "Triple spiral"],
      correctAnswer: "Double helix",
      xpReward: 15,
      lessonGroup: "Body & Biology",
      lessonOrder: 4,
      lessonGroupOrder: 1,
      lessonContent:
        "DNA (deoxyribonucleic acid) is shaped like a twisted ladder — a double helix.\nThe 'rails' are sugar-phosphate backbones, the 'rungs' are base pairs (A-T, C-G).\nWatson and Crick discovered the structure in 1953, winning the Nobel Prize.\nIf your DNA were stretched out, it would reach from Earth to the Sun and back 600 times!",
      correctExplanation: "Correct! DNA is a double helix — two strands twisted together like a spiral staircase. Watson and Crick discovered this structure in 1953.",
      incorrectExplanation: "DNA has a double helix shape — like a twisted ladder. The two strands wind around each other, held together by base pairs (Adenine-Thymine and Cytosine-Guanine).",
    },

    // ========================================================================
    // SCIENCE — Group 2: Physics Fun
    // ========================================================================
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "easy",
      title: "Gravity Rules",
      question: "If you drop a feather and a hammer on the Moon at the same time (with no air), which hits the ground first?",
      choices: ["The hammer", "The feather", "Both at the same time", "Neither — they float"],
      correctAnswer: "Both at the same time",
      xpReward: 10,
      lessonGroup: "Physics Fun",
      lessonOrder: 1,
      lessonGroupOrder: 2,
      lessonContent:
        "Apollo 15 astronaut David Scott actually did this experiment on the Moon!\nWithout air resistance, all objects fall at the same rate regardless of mass.\nEarth's gravity accelerates everything at 9.8 m/s² (in a vacuum).\nAristotle thought heavier objects fall faster — Galileo proved him wrong.",
      correctExplanation: "Right! On the Moon there's no air, so no air resistance. Both fall at the same rate and hit the ground simultaneously — just like the Apollo 15 astronaut demonstrated!",
      incorrectExplanation: "Both hit at the same time! Without air resistance, gravity accelerates all objects equally. On Earth, air slows the feather, but on the airless Moon, they fall together — proven by Apollo 15 astronauts.",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "easy",
      title: "Energy Everywhere",
      question: "What type of energy does a moving car have?",
      choices: ["Potential energy", "Kinetic energy", "Chemical energy", "Nuclear energy"],
      correctAnswer: "Kinetic energy",
      xpReward: 10,
      lessonGroup: "Physics Fun",
      lessonOrder: 2,
      lessonGroupOrder: 2,
      lessonContent:
        "Kinetic energy is the energy of motion — anything that moves has it.\nThe formula: KE = ½mv² (mass × velocity squared).\nA car going 60 mph has 4× the kinetic energy of one going 30 mph (velocity squared!).\nPotential energy is 'stored' energy (like a parked car on a hill).",
      correctExplanation: "Yes! Kinetic energy is the energy an object has due to its motion. The car's gasoline (chemical energy) is converted into kinetic energy to move it.",
      incorrectExplanation: "A moving car has kinetic energy — the energy of motion. The faster it goes, the more kinetic energy it has (KE = ½ × mass × velocity²). The gasoline stored chemical energy that gets converted into motion.",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "medium",
      title: "Light & Sound",
      question: "Which travels faster — light or sound?",
      choices: ["Light", "Sound", "They travel at the same speed", "It depends on the weather"],
      correctAnswer: "Light",
      xpReward: 15,
      lessonGroup: "Physics Fun",
      lessonOrder: 3,
      lessonGroupOrder: 2,
      lessonContent:
        "Light travels at 299,792,458 meters per second (about 300,000 km/s).\nSound travels at only 343 meters per second (about 1,235 km/h).\nThat's why you see lightning BEFORE you hear thunder!\nLight is nearly 900,000 times faster than sound.",
      correctExplanation: "Correct! Light is about 900,000× faster than sound. That's why you see lightning before you hear thunder — and why the flash of a distant explosion reaches you before the boom.",
      incorrectExplanation: "Light is much faster! Light travels at ~300,000 km/s, while sound is only ~343 m/s. The delay between lightning flash and thunder lets you estimate distance: 3 seconds ≈ 1 km away.",
    },
    {
      type: "true-false",
      category: "science",
      difficulty: "medium",
      title: "Newton's Laws",
      question: "If you're in a moving car and suddenly stop, you lurch forward because of Newton's First Law of Motion.",
      choices: ["True", "False"],
      correctAnswer: "True",
      xpReward: 15,
      lessonGroup: "Physics Fun",
      lessonOrder: 4,
      lessonGroupOrder: 2,
      lessonContent:
        "Newton's First Law: An object in motion stays in motion unless acted on by an external force.\nThis is called inertia — the tendency to resist changes in motion.\nYour body continues moving forward when the car stops (because no force stopped YOU yet).\nSeatbelts provide the external force to stop YOU safely too!",
      correctExplanation: "True! Newton's First Law (inertia): your body keeps moving forward because no force stopped it. The car stopped, but you didn't — until the seatbelt provides the force!",
      incorrectExplanation: "It's true! Newton's First Law says objects in motion stay in motion. When the car brakes, your body continues forward at the same speed until something (seatbelt/dashboard) stops you.",
    },

    // ========================================================================
    // SCIENCE — Group 3: Earth & Space
    // ========================================================================
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "easy",
      title: "Solar System",
      question: "Which planet is closest to the Sun?",
      choices: ["Venus", "Mercury", "Mars", "Earth"],
      correctAnswer: "Mercury",
      xpReward: 10,
      lessonGroup: "Earth & Space",
      lessonOrder: 1,
      lessonGroupOrder: 3,
      lessonContent:
        "Mercury is the smallest planet in our solar system (only slightly larger than Earth's Moon).\nDespite being closest to the Sun, it's NOT the hottest — Venus is hotter due to greenhouse effect.\nA year on Mercury is just 88 Earth days.\nMercury has no atmosphere, so temperatures swing from -180°C at night to 430°C in the day.",
      correctExplanation: "Correct! Mercury is the closest planet to the Sun, orbiting at about 58 million km. But Venus is actually hotter despite being farther away!",
      incorrectExplanation: "Mercury is closest to the Sun at about 58 million km. Interesting fact: Venus is actually hotter than Mercury because its thick atmosphere creates a runaway greenhouse effect.",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "easy",
      title: "Weather Wonders",
      question: "What causes a rainbow?",
      choices: ["Reflection of moonlight", "Refraction of sunlight in water droplets", "UV radiation", "Volcanic ash"],
      correctAnswer: "Refraction of sunlight in water droplets",
      xpReward: 10,
      lessonGroup: "Earth & Space",
      lessonOrder: 2,
      lessonGroupOrder: 3,
      lessonContent:
        "Rainbows form when sunlight enters a water droplet, bends (refracts), reflects off the back, and bends again as it exits.\nEach color bends at a slightly different angle, separating white light into colors.\nROYGBIV: Red, Orange, Yellow, Green, Blue, Indigo, Violet.\nYou can only see a rainbow with the Sun behind you and rain ahead of you.",
      correctExplanation: "Yes! Sunlight refracts (bends) through water droplets in the air, separating into its component colors — like a prism. The full circle is actually a complete circle; we only see the half above the horizon!",
      incorrectExplanation: "Rainbows are caused by sunlight refracting through water droplets. Each color bends at a different angle, separating white sunlight into the visible spectrum: red, orange, yellow, green, blue, indigo, violet.",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "medium",
      title: "Rocks & Minerals",
      question: "What type of rock is formed from cooled magma or lava?",
      choices: ["Sedimentary", "Igneous", "Metamorphic", "Fossilized"],
      correctAnswer: "Igneous",
      xpReward: 15,
      lessonGroup: "Earth & Space",
      lessonOrder: 3,
      lessonGroupOrder: 3,
      lessonContent:
        "Igneous rocks form when magma (underground) or lava (on surface) cools and solidifies.\n'Igneous' comes from Latin 'ignis' meaning fire.\nExamples: granite (cooled slowly underground), obsidian (cooled quickly on surface).\nThe three rock types: igneous, sedimentary, and metamorphic — all connected in the rock cycle.",
      correctExplanation: "Correct! Igneous rocks form from cooled magma/lava. Granite (slow cooling, large crystals) and obsidian (fast cooling, glassy) are both igneous.",
      incorrectExplanation: "Igneous rocks form from cooled magma or lava. 'Igneous' means 'fire-made'. Sedimentary rocks form from compressed sediments, metamorphic from heat/pressure transformation of existing rocks.",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "medium",
      title: "Ocean Depths",
      question: "What percentage of Earth's surface is covered by oceans?",
      choices: ["About 50%", "About 71%", "About 85%", "About 60%"],
      correctAnswer: "About 71%",
      xpReward: 15,
      lessonGroup: "Earth & Space",
      lessonOrder: 4,
      lessonGroupOrder: 3,
      lessonContent:
        "Oceans cover about 71% of Earth's surface — that's why Earth looks blue from space.\nThe Pacific Ocean is the largest, covering about 30% of Earth's surface (more than all land combined!).\nThe average ocean depth is about 3,700 meters (12,100 feet).\nWe've explored less than 20% of the ocean — more than 80% remains unmapped!",
      correctExplanation: "Correct! About 71% of Earth is covered by oceans. We've actually mapped more of Mars than we have of Earth's ocean floor!",
      incorrectExplanation: "Oceans cover about 71% of Earth's surface. The Pacific alone covers more area than all of Earth's landmasses combined. And over 80% of the ocean remains unexplored!",
    },

    // ========================================================================
    // SCIENCE — Group 4: Crazy Chemistry
    // ========================================================================
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "easy",
      title: "Elementary!",
      question: "What is the chemical symbol for water?",
      choices: ["W", "H2O", "WO", "H2"],
      correctAnswer: "H2O",
      xpReward: 10,
      lessonGroup: "Crazy Chemistry",
      lessonOrder: 1,
      lessonGroupOrder: 4,
      lessonContent:
        "H₂O means 2 hydrogen atoms + 1 oxygen atom per water molecule.\nWater is the 'universal solvent' — it dissolves more substances than any other liquid.\nSolid water (ice) is LESS dense than liquid water — that's why ice floats!\nWithout this property, aquatic life would freeze solid in winter.",
      correctExplanation: "Yes! H₂O = 2 Hydrogen + 1 Oxygen atoms. Water's unique properties (like ice floating) make life on Earth possible.",
      incorrectExplanation: "Water is H₂O — two hydrogen atoms bonded to one oxygen atom. The 2 is subscripted: H₂O. Water's ability to dissolve many substances makes it essential for life.",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "medium",
      title: "Reaction Time",
      question: "What happens when you mix vinegar and baking soda?",
      choices: ["They form salt", "They create an acid", "They produce carbon dioxide gas", "Nothing happens"],
      correctAnswer: "They produce carbon dioxide gas",
      xpReward: 15,
      lessonGroup: "Crazy Chemistry",
      lessonOrder: 2,
      lessonGroupOrder: 4,
      lessonContent:
        "Vinegar (acetic acid) + baking soda (sodium bicarbonate) → carbon dioxide + water + sodium acetate.\nThe fizzing bubbles are CO₂ gas being released.\nThis is an acid-base reaction — the classic 'volcano' science experiment.\nThe same reaction makes bread rise (baking powder reacts with liquid to produce CO₂ bubbles).",
      correctExplanation: "Correct! The acid (vinegar) reacts with the base (baking soda) to produce carbon dioxide gas — that's the fizzing you see!",
      incorrectExplanation: "They react to produce carbon dioxide gas — that's the fizzing and bubbling you see. The chemical equation: CH₃COOH + NaHCO₃ → CO₂ + H₂O + CH₃COONa (vinegar + baking soda → CO₂ + water + sodium acetate).",
    },
    {
      type: "true-false",
      category: "science",
      difficulty: "easy",
      title: "Kitchen Chemistry",
      question: "Adding salt to water raises its boiling point.",
      choices: ["True", "False"],
      correctAnswer: "True",
      xpReward: 10,
      lessonGroup: "Crazy Chemistry",
      lessonOrder: 3,
      lessonGroupOrder: 4,
      lessonContent:
        "Salt raises water's boiling point — called 'boiling point elevation'.\nPure water boils at 100°C (212°F). Adding salt raises it slightly.\nThis is why we add salt to pasta water — for flavor, NOT to make it boil faster (that's a myth!).\nThe effect is small: 1 teaspoon of salt in 1 liter of water raises the boiling point by only about 0.01°C.",
      correctExplanation: "True! Salt does raise the boiling point of water (boiling point elevation). But the effect is tiny — the main reason we salt pasta water is for flavor, not speed.",
      incorrectExplanation: "True! Salt increases water's boiling point (a colligative property called boiling point elevation). But the effect is small — about 0.5°C for typical pasta water. The main reason to salt pasta water IS flavor, though!",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "medium",
      title: "Famous Scientists",
      question: "Which scientist developed the theory of general relativity?",
      choices: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"],
      correctAnswer: "Albert Einstein",
      xpReward: 15,
      lessonGroup: "Crazy Chemistry",
      lessonOrder: 4,
      lessonGroupOrder: 4,
      lessonContent:
        "Einstein published General Relativity in 1915 — it describes gravity as the curvature of spacetime.\nHis famous equation E=mc² came from Special Relativity (1905).\nGeneral Relativity predicted black holes, gravitational waves (confirmed 2015), and gravitational lensing.\nEinstein's work revolutionized our understanding of space, time, and the universe.",
      correctExplanation: "Correct! Einstein developed General Relativity in 1915, describing gravity as the curvature of spacetime. Newton developed classical gravity, Galileo studied motion, and Tesla worked on electricity.",
      incorrectExplanation: "Albert Einstein developed General Relativity (1915), which replaced Newton's view of gravity. Newton's gravity works for everyday situations, but Einstein's explains black holes, the Universe's expansion, and GPS satellite timing corrections.",
    },

    // ========================================================================
    // SCIENCE — Group 5: Science Mix
    // ========================================================================
    {
      type: "true-false",
      category: "science",
      difficulty: "easy",
      title: "Funny Science Facts",
      question: "A day on Venus is longer than a year on Venus.",
      choices: ["True", "False"],
      correctAnswer: "True",
      xpReward: 10,
      lessonGroup: "Science Mix",
      lessonOrder: 1,
      lessonGroupOrder: 5,
      lessonContent:
        "Venus takes 243 Earth days to rotate ONCE on its axis (a day).\nBut it takes only 225 Earth days to orbit the Sun (a year).\nSo a Venusian day is longer than a Venusian year!\nVenus also rotates backwards compared to most planets (retrograde rotation).",
      correctExplanation: "True! A Venus day = 243 Earth days (rotation). A Venus year = 225 Earth days (orbit). So the day is longer than the year — and the Sun rises in the west there!",
      incorrectExplanation: "Believe it or not, it's true! Venus rotates extremely slowly — one full rotation takes 243 Earth days, while orbiting the Sun takes only 225 Earth days. So a Venusian day > a Venusian year.",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "medium",
      title: "Science Blunders",
      question: "What did early astronomers think the 'canals' on Mars were?",
      choices: [
        "Evidence of alien irrigation",
        "Cracks in the surface",
        "Dried-up riverbeds",
        "Volcanic fissures",
      ],
      correctAnswer: "Evidence of alien irrigation",
      xpReward: 15,
      lessonGroup: "Science Mix",
      lessonOrder: 2,
      lessonGroupOrder: 5,
      lessonContent:
        "In 1877, astronomer Giovanni Schiaparelli observed lines on Mars and called them 'canali' (channels).\nBut 'canali' was mistranslated to English as 'canals' (artificial waterways).\nThis sparked decades of belief in Martian civilization!\nWe now know they were optical illusions — the lines don't actually exist.",
      correctExplanation: "Correct! 'Canali' was mistranslated from Italian as 'canals' instead of 'channels', leading many to believe intelligent Martians built irrigation systems. A classic science translation blunder!",
      incorrectExplanation: "They were misinterpreted as artificial canals built by intelligent Martians! The Italian word 'canali' meant channels (natural), but was mistranslated to 'canals' (man-made). This sparked a belief in Martian civilization that lasted decades.",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "medium",
      title: "How Stuff Works",
      question: "How does a microwave oven heat food?",
      choices: [
        "It uses hot air",
        "It uses infrared radiation",
        "It makes water molecules vibrate using microwaves",
        "It uses convection",
      ],
      correctAnswer: "It makes water molecules vibrate using microwaves",
      xpReward: 15,
      lessonGroup: "Science Mix",
      lessonOrder: 3,
      lessonGroupOrder: 5,
      lessonContent:
        "Microwaves are electromagnetic waves at 2.45 GHz (about 12 cm wavelength).\nThey cause water molecules in food to vibrate rapidly, creating heat through friction.\nThis is why 'dry' foods (like bread) don't heat well — less water content.\nMetal sparks in microwaves because it reflects the waves, creating electric arcs.",
      correctExplanation: "Yes! Microwaves at 2.45 GHz specifically excite water molecules, making them vibrate and generate heat. That's why food with more water heats faster!",
      incorrectExplanation: "Microwaves work by emitting 2.45 GHz radiation that causes water molecules to vibrate rapidly. The vibration creates friction, which generates heat. Metal objects reflect these waves, causing sparking.",
    },
    {
      type: "multiple-choice",
      category: "science",
      difficulty: "hard",
      title: "Science Quiz Bowl",
      question: "Which of these is NOT a state of matter?",
      choices: ["Plasma", "Bose-Einstein condensate", "Energy", "Liquid crystal"],
      correctAnswer: "Energy",
      xpReward: 20,
      lessonGroup: "Science Mix",
      lessonOrder: 4,
      lessonGroupOrder: 5,
      lessonContent:
        "The four classical states: solid, liquid, gas, plasma.\nMore exotic states: Bose-Einstein condensate (BEC), fermionic condensate, liquid crystal.\nEnergy is NOT a state of matter — it's a property or quantity.\nEinstein showed matter and energy are related (E=mc²), but they're different concepts.\nPlasma is the most common state of matter in the universe (stars are plasma)!",
      correctExplanation: "Correct! Energy is not a state of matter — it's a property that matter can have. Plasma and Bose-Einstein condensate are real states of matter. Energy is measured in joules, not matter.",
      incorrectExplanation: "Energy is not a state of matter. The classical states are solid, liquid, gas, plasma. Bose-Einstein condensates and liquid crystals are real (and won Nobel Prizes). Energy is what matter CAN have, not a form it takes.",
    },

    // ========================================================================
    // PUZZLES — Group 1: Number Crunch
    // ========================================================================
    {
      type: "type-answer",
      category: "puzzles",
      difficulty: "easy",
      title: "Number Sequence",
      question: "What's the next number?\n1, 1, 2, 3, 5, 8, 13, ?",
      correctAnswer: "21",
      acceptedAnswers: ["21", "twenty-one", "twenty one"],
      xpReward: 10,
      lessonGroup: "Number Crunch",
      lessonOrder: 1,
      lessonGroupOrder: 1,
      lessonContent:
        "This is the Fibonacci sequence — each number is the sum of the two before it.\nNamed after Leonardo of Pisa (Fibonacci), who introduced it to Europe in 1202.\nFibonacci appears in nature: pinecones, sunflowers, seashells.\nThe ratio of consecutive numbers approaches the 'golden ratio' (1.618...).",
      correctExplanation: "Yes! 8 + 13 = 21. The Fibonacci sequence appears everywhere in nature — from pinecones to galaxy spirals!",
      incorrectExplanation: "The answer is 21. In the Fibonacci sequence, each number is the sum of the previous two: 1+1=2, 1+2=3, 2+3=5, 3+5=8, 5+8=13, so 8+13=21.",
    },
    {
      type: "multiple-choice",
      category: "puzzles",
      difficulty: "easy",
      title: "Math Magic",
      question: "What is 7 × 8 + 7?",
      choices: ["56", "63", "49", "58"],
      correctAnswer: "63",
      xpReward: 10,
      lessonGroup: "Number Crunch",
      lessonOrder: 2,
      lessonGroupOrder: 1,
      lessonContent:
        "Order of operations: multiplication before addition.\n7 × 8 = 56, then 56 + 7 = 63.\nAlternatively: 7 × 8 + 7 = 7 × (8 + 1) = 7 × 9 = 63.\nClever factoring can make mental math much faster!",
      correctExplanation: "Correct! 7 × 8 = 56, then 56 + 7 = 63. Or think of it as 7 × 9 = 63 (since 7 × 8 + 7 = 7 × 9).",
      incorrectExplanation: "The answer is 63. Multiply first: 7 × 8 = 56, then add 7 = 63. Alternatively, 7 × 8 + 7 = 7 × 9 = 63. The trap is forgetting order of operations.",
    },
    {
      type: "type-answer",
      category: "puzzles",
      difficulty: "medium",
      title: "The Missing Number",
      question: "Find the missing number:\n3, 7, 15, 31, ?",
      correctAnswer: "63",
      acceptedAnswers: ["63", "sixty-three", "sixty three"],
      xpReward: 15,
      lessonGroup: "Number Crunch",
      lessonOrder: 3,
      lessonGroupOrder: 1,
      lessonContent:
        "This pattern is: multiply by 2 and add 1.\n3 × 2 + 1 = 7, 7 × 2 + 1 = 15, 15 × 2 + 1 = 31.\nAnother way: each number is 2^(n+1) - 1.\n3 = 2²-1, 7 = 2³-1, 15 = 2⁴-1, 31 = 2⁵-1, so next = 2⁶-1 = 63.",
      correctExplanation: "Yes! Each number follows: × 2 + 1. 31 × 2 + 1 = 63. Or: 2⁶ - 1 = 64 - 1 = 63.",
      incorrectExplanation: "The pattern is 'double and add 1': 3→7 (×2+1), 7→15, 15→31, so 31→63 (×2+1=63). Also: all are 2^n-1: 3=2²-1, 7=2³-1... so next is 2⁶-1=63.",
    },
    {
      type: "multiple-choice",
      category: "puzzles",
      difficulty: "medium",
      title: "Prime Time",
      question: "Which of these numbers is NOT a prime number?",
      choices: ["2", "3", "17", "21"],
      correctAnswer: "21",
      xpReward: 15,
      lessonGroup: "Number Crunch",
      lessonOrder: 4,
      lessonGroupOrder: 1,
      lessonContent:
        "A prime number is only divisible by 1 and itself.\n2 is the smallest and only even prime number.\n21 = 3 × 7, so it's composite (not prime).\nThere are infinitely many primes — proven by Euclid in 300 BCE.",
      correctExplanation: "Right! 21 = 3 × 7, so it's composite. 2, 3, and 17 are all primes (2 is the only even prime).",
      incorrectExplanation: "21 is not prime because 21 = 3 × 7. Primes are only divisible by 1 and themselves. 2 is prime (the only even prime), 3 and 17 are also prime.",
    },

    // ========================================================================
    // PUZZLES — Group 2: Word Play
    // ========================================================================
    {
      type: "multiple-choice",
      category: "puzzles",
      difficulty: "easy",
      title: "Word Search",
      question: "Which of these is a word that reads the same forwards and backwards?",
      choices: ["Radar", "Pencil", "Window", "Garden"],
      correctAnswer: "Radar",
      xpReward: 10,
      lessonGroup: "Word Play",
      lessonOrder: 1,
      lessonGroupOrder: 2,
      lessonContent:
        "Words that read the same forwards and backwards are called 'palindromes'.\n'Radar', 'level', 'civic', 'racecar' are all palindromes.\nSome sentences can be palindromes: 'A man, a plan, a canal, Panama'.\nPalindromes date back to ancient Greece — the word comes from Greek 'palin' (again) + 'dromos' (direction).",
      correctExplanation: "Yes! R-A-D-A-R is a palindrome — it reads the same backwards. Other examples: racecar, level, civic, kayak.",
      incorrectExplanation: "'Radar' is a palindrome (reads same forwards and backwards). 'Pencil' reversed is 'licnep', 'Window' is 'wodniW', 'Garden' is 'nedraG'. None of those are palindromes.",
    },
    {
      type: "type-answer",
      category: "puzzles",
      difficulty: "easy",
      title: "Palindrome Party",
      question: "Give me a 5-letter palindrome that means a small boat.",
      correctAnswer: "Kayak",
      acceptedAnswers: ["Kayak", "kayak"],
      xpReward: 10,
      lessonGroup: "Word Play",
      lessonOrder: 2,
      lessonGroupOrder: 2,
      lessonContent:
        "Palindromes can be words, phrases, or even numbers.\n'Kayak' is a palindrome: K-A-Y-A-K.\nLong word palindrome: 'tattarrattat' (James Joyce's made-up word for a knock on a door).\nNumber palindromes: 121, 1331, 12321.",
      correctExplanation: "Yes! K-A-Y-A-K spells the same forwards and backwards. A kayak is a small boat traditionally used by Inuit people.",
      incorrectExplanation: "The answer is 'kayak'. It's a 5-letter palindrome (K-A-Y-A-K) meaning a small, narrow boat. Other palindromes: civic, level, radar.",
    },
    {
      type: "multiple-choice",
      category: "puzzles",
      difficulty: "medium",
      title: "Rhyme Time",
      question: "Which word rhymes with 'orange'?",
      choices: ["Range", "Sponge", "Door hinge", "None — there's no perfect rhyme"],
      correctAnswer: "None — there's no perfect rhyme",
      xpReward: 15,
      lessonGroup: "Word Play",
      lessonOrder: 3,
      lessonGroupOrder: 2,
      lessonContent:
        "'Orange' has no perfect rhyme in English! It's one of the most famous unrhyamable words.\nOther words with no perfect rhyme: silver, purple, month, ninth, pint, wolf.\n'Sporange' (a plant spore case) is the closest — but it's pronounced differently.\nThis is the basis for the phrase 'orange rhymes with nothing'.",
      correctExplanation: "Correct! 'Orange' famously has no perfect rhyme in English. 'Door hinge' is a near-rhyme (not perfect), 'range' has a different ending sound. The closest is 'sporange' (pronounced spuh-RANJ).",
      incorrectExplanation: "There is no perfect rhyme for 'orange' in English. 'Sporange' (a spore case) is the only word that rhymes if pronounced differently. Other unrhymable words: silver, purple, month, ninth.",
    },
    {
      type: "type-answer",
      category: "puzzles",
      difficulty: "medium",
      title: "Missing Vowels",
      question: "What word is this without vowels?\nSK_L_T_N",
      correctAnswer: "Skeleton",
      acceptedAnswers: ["Skeleton", "skeleton"],
      xpReward: 15,
      lessonGroup: "Word Play",
      lessonOrder: 4,
      lessonGroupOrder: 2,
      lessonContent:
        "English vowels are A, E, I, O, U (and sometimes Y).\nRemoving vowels from words creates fun puzzles.\n'Rhythm' and 'syzygy' have no vowels (Y acts as a vowel here).\nThe longest English word with no vowels? 'Tsktsks' (7 letters).",
      correctExplanation: "Right! S-K-E-L-E-T-O-N. Fill in E, E, O — the word is skeleton. The underscores represent the missing vowels.",
      incorrectExplanation: "The answer is 'skeleton'. With vowels: SkeLeTOn (E, E, O). The consonants give you the 'frame' of the word, and you fill in the vowels.",
    },

    // ========================================================================
    // PUZZLES — Group 3: Think Different
    // ========================================================================
    {
      type: "riddle",
      category: "puzzles",
      difficulty: "medium",
      title: "Lateral Thinking",
      question: "A man walks into a bar and asks for a glass of water. The bartender points a gun at him. The man says 'Thank you' and leaves. What happened?",
      correctAnswer: "The man had hiccups",
      acceptedAnswers: [
        "He had hiccups",
        "The man had hiccups",
        "Hiccups",
        "He was curing his hiccups",
      ],
      xpReward: 15,
      hintText: "Why would someone ask for water but be grateful for a scare?\nThink about medical conditions.\nThe bartender didn't WANT to shoot him.",
      lessonGroup: "Think Different",
      lessonOrder: 1,
      lessonGroupOrder: 3,
      lessonContent:
        "This is a famous lateral thinking puzzle — requiring a creative leap.\nThe man had hiccups. He asked for water to cure them.\nThe bartender recognized this and used the scare tactic instead (which also cures hiccups).\nThe man's hiccups were cured, so he thanked the bartender and left!",
      correctExplanation: "Correct! The man had hiccups and wanted water. The bartender knew a sudden scare can cure hiccups, so he pointed the gun. It worked — hiccups gone, hence the 'thank you'!",
      incorrectExplanation: "The man had hiccups! He asked for water to cure them. The bartender, recognizing this, used a sudden scare instead (a known hiccup cure). It worked, so the man thanked him. The puzzle requires thinking of medical context.",
    },
    {
      type: "multiple-choice",
      category: "puzzles",
      difficulty: "medium",
      title: "What's in Common?",
      question: "What do these three things have in common?\nA. A birthday candle\nB. A wedding ring\nC. A traffic light",
      choices: [
        "They're all circular",
        "They all involve change or life events",
        "They're all made of metal",
        "They're all dangerous",
      ],
      correctAnswer: "They all involve change or life events",
      xpReward: 15,
      lessonGroup: "Think Different",
      lessonOrder: 2,
      lessonGroupOrder: 3,
      lessonContent:
        "Connection puzzles test your ability to find abstract links.\nBirthday candle → aging/celebration.\nWedding ring → marriage/commitment.\nTraffic light → direction/change.\nAll three represent TRANSITIONS or CHANGES in life or state.",
      correctExplanation: "Yes! All three mark transitions: a birthday candle marks aging, a wedding ring marks marital status change, a traffic light signals safe/stop transitions.",
      incorrectExplanation: "They all relate to change/transitions. A birthday candle marks another year (growing up), a wedding ring marks marriage (life change), a traffic light signals a state change (stop/go). The common theme is 'change'.",
    },
    {
      type: "multiple-choice",
      category: "puzzles",
      difficulty: "hard",
      title: "The Unexpected",
      question: "You have a 3-gallon jug and a 5-gallon jug. How can you measure exactly 4 gallons?",
      choices: [
        "Fill 3, pour into 5, fill 3 again, pour into 5 until full — 1 remains in 3, empty 5, pour the 1 into 5, fill 3 again, pour into 5 = 4",
        "Fill 5, pour into 3 — 2 remains, empty 3, pour the 2 into 3, fill 5 again, pour into 3 until full = 4 in 5",
        "Both methods work",
        "It's impossible",
      ],
      correctAnswer: "Both methods work",
      xpReward: 20,
      lessonGroup: "Think Different",
      lessonOrder: 3,
      lessonGroupOrder: 3,
      lessonContent:
        "This classic 'water jug' puzzle was featured in the movie Die Hard with a Vengeance.\nIt teaches state-space search — exploring possible actions.\nAction types: fill, empty, or pour between jugs.\nBoth approaches work because the math is symmetric (gcd of 3 and 5 = 1, so any amount from 1-5 is measurable).",
      correctExplanation: "Yes! Both methods work. Method 1: Fill 3→5, Fill 3→5 (1 left), Empty 5→Pour 1→Fill 3→Pour=4 in 5. Method 2: Fill 5→3 (2 left), Empty 3→Pour 2→Fill 5→Pour=4 in 5.",
      incorrectExplanation: "Both methods work because 3 and 5 are coprime (GCD=1). The puzzle is a classic example of using a state-space search to solve measurement problems.",
    },
    {
      type: "multiple-choice",
      category: "puzzles",
      difficulty: "hard",
      title: "Reverse Psychology",
      question: "If the day after tomorrow is three days before Saturday, what day is today?",
      choices: ["Monday", "Tuesday", "Wednesday", "Thursday"],
      correctAnswer: "Monday",
      xpReward: 20,
      lessonGroup: "Think Different",
      lessonOrder: 4,
      lessonGroupOrder: 3,
      lessonContent:
        "Work backwards one step at a time.\n'Three days before Saturday' = Wednesday (Sat→Fri, Thu, Wed).\nSo 'the day after tomorrow' = Wednesday.\nIf day after tomorrow is Wednesday → tomorrow is Tuesday → today is Monday.",
      correctExplanation: "The answer is Monday. Day after tomorrow = 3 days before Saturday = Wednesday. So tomorrow is Tuesday, today is Monday.",
      incorrectExplanation: "Let's work through it: 'Three days before Saturday' = Wednesday. 'The day after tomorrow is Wednesday' → tomorrow is Tuesday → today is Monday.",
    },

    // ========================================================================
    // PUZZLES — Group 4: Bonus Round
    // ========================================================================
    {
      type: "multiple-choice",
      category: "puzzles",
      difficulty: "easy",
      title: "Mixed Bag 1",
      question: "If you have me, you want to share me. If you share me, you don't have me. What am I?",
      choices: ["A secret", "Money", "Food", "A book"],
      correctAnswer: "A secret",
      xpReward: 10,
      lessonGroup: "Bonus Round",
      lessonOrder: 1,
      lessonGroupOrder: 4,
      lessonContent:
        "This is a paradox-style riddle based on the nature of secrets.\nA secret is only 'yours' if you don't tell anyone.\nOnce shared, it's no longer exclusively yours.\nThis highlights the interesting property of information: sharing doesn't divide it, but you 'lose' exclusive ownership.",
      correctExplanation: "Yes! A secret is something you 'have' only as long as you don't share it. Once shared, it's no longer your exclusive secret.",
      incorrectExplanation: "The answer is 'a secret'. You possess a secret as long as you don't tell anyone. But once you share it, it's no longer just your secret — you've 'lost' exclusive ownership.",
    },
    {
      type: "multiple-choice",
      category: "puzzles",
      difficulty: "medium",
      title: "Mixed Bag 2",
      question: "If a rooster lays an egg on the peak of a roof, which way does it roll?",
      choices: ["Left", "Right", "Down both sides", "Roosters don't lay eggs"],
      correctAnswer: "Roosters don't lay eggs",
      xpReward: 15,
      lessonGroup: "Bonus Round",
      lessonOrder: 2,
      lessonGroupOrder: 4,
      lessonContent:
        "Trick questions test whether you accept false premises.\nOnly female chickens (hens) lay eggs — roosters are male.\nThe question makes a false assumption (that a rooster can lay an egg).\nAlways question the premises of a problem before solving it!",
      correctExplanation: "Correct! Roosters are male chickens — they don't lay eggs! The question tricks you with a false premise. Always question your assumptions first.",
      incorrectExplanation: "Roosters don't lay eggs — only hens do! This is a classic trick question that makes you focus on the wrong detail (which way it rolls) while the real answer is exposing the false premise.",
    },
    {
      type: "true-false",
      category: "puzzles",
      difficulty: "easy",
      title: "Speed Round",
      question: "A year on Earth is 365 days.",
      choices: ["True", "False"],
      correctAnswer: "False",
      xpReward: 10,
      lessonGroup: "Bonus Round",
      lessonOrder: 3,
      lessonGroupOrder: 4,
      lessonContent:
        "A year is actually 365.2425 days long (the time for Earth to orbit the Sun).\nThat's why we have leap years every 4 years (adding Feb 29).\nBut even that's not exact — century years skip leap years unless divisible by 400.\nThe Gregorian calendar (1582) fixed previous calendar drift — by 1752, England was 11 days behind!",
      correctExplanation: "Correct — it's false! A year is actually about 365.2425 days. We add a leap day every 4 years (mostly) to catch up — that's why we have February 29th!",
      incorrectExplanation: "False! The Earth actually takes about 365.2425 days to orbit the Sun. That 'extra' 0.2425 days accumulates — which is why we add a leap day (Feb 29) every 4 years to keep our calendar aligned.",
    },
    {
      type: "multiple-choice",
      category: "puzzles",
      difficulty: "hard",
      title: "Final Challenge",
      question: "You have two ropes. Each takes exactly 60 minutes to burn, but they burn unevenly (not at a constant rate). How can you measure exactly 45 minutes?",
      choices: [
        "Fold one rope in half, cut both ropes in quarters",
        "Light both ends of one rope AND one end of the other simultaneously",
        "Light one rope from both ends (30 min) and the other from both ends (30 min) — overlap = 15 min",
        "Light Rope A at both ends and Rope B at one end. When A burns out (30 min), light B's other end. When B burns out, 45 min total",
      ],
      correctAnswer: "Light Rope A at both ends and Rope B at one end. When A burns out (30 min), light B's other end. When B burns out, 45 min total",
      xpReward: 25,
      lessonGroup: "Bonus Round",
      lessonOrder: 4,
      lessonGroupOrder: 4,
      lessonContent:
        "This puzzle is a classic interview question at companies like Google and Microsoft.\nKey insight: a rope lit from both ends burns in 30 min (60/2).\nRope A lit from both ends = 30 min timer.\nWhen A is done, Rope B has 30 min left. Lighting its other end halves the remaining time to 15 min.\n30 + 15 = 45 minutes total.",
      correctExplanation: "Correct! Step 1: Light Rope A (both ends) + Rope B (one end). Step 2: When A burns out (30 min), light B's other end. Step 3: B burns out in 15 more min (half of remaining 30). Total = 45 min.",
      incorrectExplanation: "The solution: Light rope A at both ends AND rope B at one end simultaneously. When A burns out (30 min), light the other end of B (which has 30 min left). B now burns from both ends and finishes in 15 min. Total: 30 + 15 = 45 min.",
    },
  ],
};

export default seedData;
